/**
 * Real cards for the substitute ranker tests (Scryfall oracle_cards, 2026-09-29
 * bulk). Text copied verbatim from the bulk file; no labels here.
 */
import type { FactsInputCard } from '../cardFacts/schema';

export const SUBSTITUTE_TEST_CARDS: Record<string, FactsInputCard> = {
  'Grave Pact': {
    oracle_id: '6f4ac4a4-53ec-4bc9-8f5c-d4b801d867b2',
    name: 'Grave Pact',
    layout: 'normal',
    type_line: 'Enchantment',
    mana_cost: '{1}{B}{B}{B}',
    oracle_text:
      'Whenever a creature you control dies, each other player sacrifices a creature of their choice.',
    keywords: [],
    cmc: 4,
  },
  'Dictate of Erebos': {
    oracle_id: '7c777a41-e40a-4b40-96bf-8ddd5c12924c',
    name: 'Dictate of Erebos',
    layout: 'normal',
    type_line: 'Enchantment',
    mana_cost: '{3}{B}{B}',
    oracle_text:
      'Flash\nWhenever a creature you control dies, each opponent sacrifices a creature of their choice.',
    keywords: ['Flash'],
    cmc: 5,
  },
  'Butcher of Malakir': {
    oracle_id: 'a85197ab-dc94-4b72-9716-8dbdbbe90ff8',
    name: 'Butcher of Malakir',
    layout: 'normal',
    type_line: 'Creature — Vampire Warrior',
    mana_cost: '{5}{B}{B}',
    oracle_text:
      'Flying\nWhenever this creature or another creature you control dies, each opponent sacrifices a creature of their choice.',
    keywords: ['Flying'],
    power: '5',
    toughness: '4',
    cmc: 7,
  },
  'Zulaport Cutthroat': {
    oracle_id: '76b003e0-15af-4f22-bdf2-1ade5430964a',
    name: 'Zulaport Cutthroat',
    layout: 'normal',
    type_line: 'Creature — Human Rogue Ally',
    mana_cost: '{1}{B}',
    oracle_text:
      'Whenever this creature or another creature you control dies, each opponent loses 1 life and you gain 1 life.',
    keywords: [],
    power: '1',
    toughness: '1',
    cmc: 2,
  },
  'Massacre Wurm': {
    oracle_id: '93cf50cf-0ecc-4d3e-abea-778c1ebacec4',
    name: 'Massacre Wurm',
    layout: 'normal',
    type_line: 'Creature — Phyrexian Wurm',
    mana_cost: '{3}{B}{B}{B}',
    oracle_text:
      'When this creature enters, creatures your opponents control get -2/-2 until end of turn.\nWhenever a creature an opponent controls dies, that player loses 2 life.',
    keywords: [],
    power: '6',
    toughness: '5',
    cmc: 6,
  },
  'Blood Artist': {
    oracle_id: '310f141c-7f37-4729-aed6-dd9c09db448d',
    name: 'Blood Artist',
    layout: 'normal',
    type_line: 'Creature — Vampire',
    mana_cost: '{1}{B}',
    oracle_text:
      'Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life.',
    keywords: [],
    power: '0',
    toughness: '1',
    cmc: 2,
  },
  'Swords to Plowshares': {
    oracle_id: 'b1544f21-7e98-461b-aed5-e748b0168c52',
    name: 'Swords to Plowshares',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{W}',
    oracle_text: 'Exile target creature. Its controller gains life equal to its power.',
    keywords: [],
    cmc: 1,
  },
  'Path to Exile': {
    oracle_id: 'd683d985-9888-4d21-8b5f-69e69ce4a03b',
    name: 'Path to Exile',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{W}',
    oracle_text:
      'Exile target creature. Its controller may search their library for a basic land card, put that card onto the battlefield tapped, then shuffle.',
    keywords: [],
    cmc: 1,
  },
  Vindicate: {
    oracle_id: '63c1ac21-e3d8-40c2-8c09-3f31c52992ef',
    name: 'Vindicate',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{1}{W}{B}',
    oracle_text: 'Destroy target permanent.',
    keywords: [],
    cmc: 3,
  },
  Counterspell: {
    oracle_id: 'cc187110-1148-4090-bbb8-e205694a39f5',
    name: 'Counterspell',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{U}{U}',
    oracle_text: 'Counter target spell.',
    keywords: [],
    cmc: 2,
  },
  Negate: {
    oracle_id: '3407fe41-fdd3-4119-8f70-4bc4590a379f',
    name: 'Negate',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{U}',
    oracle_text: 'Counter target noncreature spell.',
    keywords: [],
    cmc: 2,
  },
  'Arcane Signet': {
    oracle_id: '0bc7f093-bef0-4f1a-852c-4b75ebf54838',
    name: 'Arcane Signet',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{2}',
    oracle_text: "{T}: Add one mana of any color in your commander's color identity.",
    keywords: [],
    cmc: 2,
  },
  'Mind Stone': {
    oracle_id: 'c97361b5-af16-4a7b-af85-a429dbaf4ad2',
    name: 'Mind Stone',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{2}',
    oracle_text: '{T}: Add {C}.\n{1}, {T}, Sacrifice this artifact: Draw a card.',
    keywords: [],
    cmc: 2,
  },
  Cultivate: {
    oracle_id: '8b755881-a72d-4e21-a369-d2924eb4585a',
    name: 'Cultivate',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{2}{G}',
    oracle_text:
      'Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.',
    keywords: [],
    cmc: 3,
  },
  'Wrath of God': {
    oracle_id: '34515b16-c9a4-4f98-8c77-416a7a523407',
    name: 'Wrath of God',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{2}{W}{W}',
    oracle_text: "Destroy all creatures. They can't be regenerated.",
    keywords: [],
    cmc: 4,
  },
  'Rhystic Study': {
    oracle_id: '53236dd7-845a-444c-96d5-f41ed7325d8f',
    name: 'Rhystic Study',
    layout: 'normal',
    type_line: 'Enchantment',
    mana_cost: '{2}{U}',
    oracle_text:
      'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.',
    keywords: [],
    cmc: 3,
  },
  'Viscera Seer': {
    oracle_id: 'f82a4e85-526d-4456-b700-7760043a31be',
    name: 'Viscera Seer',
    layout: 'normal',
    type_line: 'Creature — Vampire Wizard',
    mana_cost: '{B}',
    oracle_text:
      'Sacrifice a creature: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)',
    keywords: ['Scry'],
    power: '1',
    toughness: '1',
    cmc: 1,
  },
  'Carrion Feeder': {
    oracle_id: 'a1cc5e37-b09a-4b7f-afd5-77c1c35aa425',
    name: 'Carrion Feeder',
    layout: 'normal',
    type_line: 'Creature — Zombie',
    mana_cost: '{B}',
    oracle_text:
      "This creature can't block.\nSacrifice a creature: Put a +1/+1 counter on this creature.",
    keywords: [],
    power: '1',
    toughness: '1',
    cmc: 1,
  },
  'Doomed Traveler': {
    oracle_id: 'a30907c0-fbde-4fd3-a8c7-f304305fcea7',
    name: 'Doomed Traveler',
    layout: 'normal',
    type_line: 'Creature — Human Soldier',
    mana_cost: '{W}',
    oracle_text: 'When this creature dies, create a 1/1 white Spirit creature token with flying.',
    keywords: [],
    power: '1',
    toughness: '1',
    cmc: 1,
  },
  Bitterblossom: {
    oracle_id: 'fb868840-09fa-49b1-85cb-b08ad065e972',
    name: 'Bitterblossom',
    layout: 'normal',
    type_line: 'Kindred Enchantment — Faerie',
    mana_cost: '{1}{B}',
    oracle_text:
      'At the beginning of your upkeep, you lose 1 life and create a 1/1 black Faerie Rogue creature token with flying.',
    keywords: [],
    cmc: 2,
  },
  "Ashnod's Altar": {
    oracle_id: '4d18bcba-a346-445e-a182-6cc30b7e066d',
    name: "Ashnod's Altar",
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{3}',
    oracle_text: 'Sacrifice a creature: Add {C}{C}.',
    keywords: [],
    cmc: 3,
  },
  'Pitiless Plunderer': {
    oracle_id: 'a784481f-eccb-4112-bb38-04a659319660',
    name: 'Pitiless Plunderer',
    layout: 'normal',
    type_line: 'Creature — Human Pirate',
    mana_cost: '{3}{B}',
    oracle_text:
      'Whenever another creature you control dies, create a Treasure token. (It\'s an artifact with "{T}, Sacrifice this token: Add one mana of any color.")',
    keywords: ['Treasure'],
    power: '1',
    toughness: '4',
    cmc: 4,
  },
  'Sol Ring': {
    oracle_id: '6ad8011d-3471-4369-9d68-b264cc027487',
    name: 'Sol Ring',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{1}',
    oracle_text: '{T}: Add {C}{C}.',
    keywords: [],
    cmc: 1,
  },
  'Doom Blade': {
    oracle_id: '59e7f2ae-4535-4191-98be-3e65b6b2befa',
    name: 'Doom Blade',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{B}',
    oracle_text: 'Destroy target nonblack creature.',
    keywords: [],
    cmc: 2,
  },
};
