// Format staple cards by color
// These cards are highly played across most EDH decks

export const FORMAT_STAPLES = {
  colorless: [
    'Sol Ring',
    'Arcane Signet',
    'Command Tower',
    'Lightning Greaves',
    'Swiftfoot Boots',
    'Thought Vessel',
    'Mind Stone',
    "Commander's Sphere",
    "Wayfarer's Bauble",
    'Reliquary Tower',
  ],
  W: [
    'Swords to Plowshares',
    'Path to Exile',
    'Smothering Tithe',
    "Teferi's Protection",
    'Generous Gift',
    'Austere Command',
    'Wrath of God',
    'Sun Titan',
    'Esper Sentinel',
    'Farewell',
  ],
  U: [
    'Counterspell',
    'Cyclonic Rift',
    'Rhystic Study',
    'Mystic Remora',
    'Ponder',
    'Brainstorm',
    'Swan Song',
    'Fierce Guardianship',
    'Fact or Fiction',
    'Consecrated Sphinx',
  ],
  B: [
    'Demonic Tutor',
    'Toxic Deluge',
    'Feed the Swarm',
    'Reanimate',
    'Animate Dead',
    'Phyrexian Arena',
    'Vampiric Tutor',
    'Damnation',
    'Grave Pact',
    'Black Market Connections',
  ],
  R: [
    'Chaos Warp',
    'Blasphemous Act',
    'Dockside Extortionist',
    'Wheel of Fortune',
    'Deflecting Swat',
    "Jeska's Will",
    'Gamble',
    'Vandalblast',
    'Faithless Looting',
    'Goldspan Dragon',
  ],
  G: [
    'Cultivate',
    "Kodama's Reach",
    'Beast Within',
    'Eternal Witness',
    'Birds of Paradise',
    'Sylvan Library',
    "Nature's Claim",
    'Heroic Intervention',
    'Rampant Growth',
    'Three Visits',
  ],
};

// Staples by category
export const CATEGORY_STAPLES = {
  ramp: [
    'Sol Ring',
    'Arcane Signet',
    'Cultivate',
    "Kodama's Reach",
    'Mind Stone',
    'Thought Vessel',
    "Commander's Sphere",
    'Fellwar Stone',
    'Rampant Growth',
    "Nature's Lore",
    'Three Visits',
    'Farseek',
    'Birds of Paradise',
    'Llanowar Elves',
    'Elvish Mystic',
    'Dockside Extortionist',
    'Smothering Tithe',
    'Mana Crypt',
    'Chrome Mox',
    'Mox Diamond',
  ],
  cardDraw: [
    'Rhystic Study',
    'Mystic Remora',
    'Phyrexian Arena',
    'Sylvan Library',
    'Esper Sentinel',
    'Black Market Connections',
    'Ponder',
    'Brainstorm',
    'Preordain',
    "Night's Whisper",
    'Read the Bones',
    'Sign in Blood',
    'Beast Whisperer',
    'Guardian Project',
    'The Great Henge',
    'Necropotence',
    'Consecrated Sphinx',
  ],
  singleRemoval: [
    'Swords to Plowshares',
    'Path to Exile',
    'Beast Within',
    'Generous Gift',
    'Chaos Warp',
    'Counterspell',
    'Swan Song',
    "Assassin's Trophy",
    'Anguished Unmaking',
    'Despark',
    "Nature's Claim",
    'Feed the Swarm',
    'Mortify',
    'Putrefy',
    'Vindicate',
    'Reality Shift',
    'Pongify',
    'Rapid Hybridization',
  ],
  boardWipes: [
    'Cyclonic Rift',
    'Toxic Deluge',
    'Wrath of God',
    'Damnation',
    'Blasphemous Act',
    'Farewell',
    'Austere Command',
    'Merciless Eviction',
    'Vanquish the Horde',
    'Supreme Verdict',
    'Ruinous Ultimatum',
    'Damn',
    'Cleansing Nova',
  ],
  utility: [
    'Lightning Greaves',
    'Swiftfoot Boots',
    'Reliquary Tower',
    'Command Tower',
    "Teferi's Protection",
    'Heroic Intervention',
    'Fierce Guardianship',
    'Deflecting Swat',
    'Force of Will',
    'Force of Negation',
  ],
};

// Archetype-specific staples
export const ARCHETYPE_STAPLES = {
  voltron: [
    'Sword of Fire and Ice',
    'Sword of Feast and Famine',
    'Shadowspear',
    'Helm of the Host',
    'Sword of Hearth and Home',
    'Sword of Truth and Justice',
    'Blackblade Reforged',
    "Umezawa's Jitte",
    'Hammer of Nazahn',
    'Puresteel Paladin',
    "Sigarda's Aid",
    'Open the Armory',
    "Steelshaper's Gift",
    'Stoneforge Mystic',
  ],
  spellslinger: [
    'Storm-Kiln Artist',
    'Guttersnipe',
    'Young Pyromancer',
    'Talrand, Sky Summoner',
    'Thousand-Year Storm',
    'Archmage Emeritus',
    'Birgi, God of Storytelling',
    'Underworld Breach',
    'Past in Flames',
    'Finale of Promise',
    "Mizzix's Mastery",
  ],
  tokens: [
    'Anointed Procession',
    'Parallel Lives',
    'Doubling Season',
    'Craterhoof Behemoth',
    'Beastmaster Ascension',
    'Divine Visitation',
    'Mondrak, Glory Dominus',
    'Rabble Rousing',
    'Elesh Norn, Grand Cenobite',
    'Coat of Arms',
    "Cathars' Crusade",
  ],
  aristocrats: [
    'Blood Artist',
    'Zulaport Cutthroat',
    'Pitiless Plunderer',
    'Grave Pact',
    'Dictate of Erebos',
    'Viscera Seer',
    'Carrion Feeder',
    "Ashnod's Altar",
    'Phyrexian Altar',
    'Reassembling Skeleton',
    'Bloodghast',
    'Yawgmoth, Thran Physician',
  ],
  reanimator: [
    'Reanimate',
    'Animate Dead',
    'Dance of the Dead',
    'Necromancy',
    'Entomb',
    'Buried Alive',
    'Life // Death',
    'Persist',
    'Victimize',
    'Living Death',
    'Rise of the Dark Realms',
    'Jin-Gitaxias, Core Augur',
  ],
  tribal: [
    "Herald's Horn",
    "Vanquisher's Banner",
    'Icon of Ancestry',
    'Door of Destinies',
    'Coat of Arms',
    "Patriarch's Bidding",
    'Kindred Discovery',
    'Kindred Dominance',
  ],
  landfall: [
    'Avenger of Zendikar',
    'Scute Swarm',
    'Lotus Cobra',
    'Tireless Provisioner',
    'Ramunap Excavator',
    'Crucible of Worlds',
    'Exploration',
    'Burgeoning',
    'Oracle of Mul Daya',
    'Azusa, Lost but Seeking',
    'Dryad of the Ilysian Grove',
    'Ancient Greenwarden',
  ],
  artifacts: [
    'Urza, Lord High Artificer',
    'Krark-Clan Ironworks',
    'Darksteel Forge',
    'Mycosynth Lattice',
    'Unwinding Clock',
    'Shimmer Myr',
    'Master Transmuter',
    'Goblin Engineer',
    'Goblin Welder',
    'Academy Manufactor',
    'Clock of Omens',
  ],
  enchantress: [
    "Enchantress's Presence",
    'Argothian Enchantress',
    'Mesa Enchantress',
    'Eidolon of Blossoms',
    'Satyr Enchanter',
    "Sythis, Harvest's Hand",
    'Sphere of Safety',
    'Ghostly Prison',
    'Propaganda',
    'Greater Auramancy',
    'Sterling Grove',
  ],
};

export function isFormatStaple(cardName: string): boolean {
  const name = cardName.toLowerCase();
  const allStaples = [
    ...FORMAT_STAPLES.colorless,
    ...FORMAT_STAPLES.W,
    ...FORMAT_STAPLES.U,
    ...FORMAT_STAPLES.B,
    ...FORMAT_STAPLES.R,
    ...FORMAT_STAPLES.G,
  ];
  return allStaples.some((staple) => staple.toLowerCase() === name);
}

export function isArchetypeStaple(cardName: string, archetype: string): boolean {
  const name = cardName.toLowerCase();
  const staples = ARCHETYPE_STAPLES[archetype as keyof typeof ARCHETYPE_STAPLES] || [];
  return staples.some((staple) => staple.toLowerCase() === name);
}
