/**
 * Real cards (Scryfall oracle_cards, 2026-09-29) for unit tests that the gold
 * sets don't already carry. Text copied verbatim; no labels here.
 */
import type { FactsInputCard } from './schema';

export const TEST_CARDS: Record<string, FactsInputCard> = {
  'Dictate of Erebos': {
    oracle_id: '7c777a41-e40a-4b40-96bf-8ddd5c12924c',
    name: 'Dictate of Erebos',
    layout: 'normal',
    type_line: 'Enchantment',
    mana_cost: '{3}{B}{B}',
    oracle_text:
      'Flash\nWhenever a creature you control dies, each opponent sacrifices a creature of their choice.',
    keywords: ['Flash'],
    cmc: 5,
  },
  'Butcher of Malakir': {
    oracle_id: 'a85197ab-dc94-4b72-9716-8dbdbbe90ff8',
    name: 'Butcher of Malakir',
    layout: 'normal',
    type_line: 'Creature — Vampire Warrior',
    mana_cost: '{5}{B}{B}',
    oracle_text:
      'Flying\nWhenever this creature or another creature you control dies, each opponent sacrifices a creature of their choice.',
    keywords: ['Flying'],
    power: '5',
    toughness: '4',
    cmc: 7,
  },
  'Savra, Queen of the Golgari': {
    oracle_id: '641db975-cf94-44c6-a391-f540a952e0d8',
    name: 'Savra, Queen of the Golgari',
    layout: 'normal',
    type_line: 'Legendary Creature — Elf Shaman',
    mana_cost: '{2}{B}{G}',
    oracle_text:
      'Whenever you sacrifice a black creature, you may pay 2 life. If you do, each other player sacrifices a creature of their choice.\nWhenever you sacrifice a green creature, you may gain 2 life.',
    keywords: [],
    power: '2',
    toughness: '2',
    cmc: 4,
  },
  'Falkenrath Noble': {
    oracle_id: '3739b179-bc81-4737-8376-66a57e16b942',
    name: 'Falkenrath Noble',
    layout: 'normal',
    type_line: 'Creature — Vampire Noble',
    mana_cost: '{3}{B}',
    oracle_text:
      'Flying\nWhenever this creature or another creature dies, target player loses 1 life and you gain 1 life.',
    keywords: ['Flying'],
    power: '2',
    toughness: '2',
    cmc: 4,
  },
  'Day of Judgment': {
    oracle_id: 'd057289d-5e28-43d5-8ff3-4a1bc723477d',
    name: 'Day of Judgment',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{2}{W}{W}',
    oracle_text: 'Destroy all creatures.',
    keywords: [],
    cmc: 4,
  },
  'Blot Out': {
    oracle_id: '9609cd5c-b537-4cb2-9dde-4b12795531f7',
    name: 'Blot Out',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{2}{B}',
    oracle_text:
      'Target opponent exiles a creature or planeswalker they control with the greatest mana value among creatures and planeswalkers they control.',
    keywords: [],
    cmc: 3,
  },
  'Temporal Trespass': {
    oracle_id: 'c216b924-88ac-4853-9e95-0c345c09eeb6',
    name: 'Temporal Trespass',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{8}{U}{U}{U}',
    oracle_text:
      'Delve (Each card you exile from your graveyard while casting this spell pays for {1}.)\nTake an extra turn after this one. Exile Temporal Trespass.',
    keywords: ['Delve'],
    cmc: 11,
  },
  'Time Warp': {
    oracle_id: 'dbd6a94b-62ff-4a10-9d52-bdd90b26e425',
    name: 'Time Warp',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{3}{U}{U}',
    oracle_text: 'Target player takes an extra turn after this one.',
    keywords: [],
    cmc: 5,
  },
  'Eon Frolicker': {
    oracle_id: 'c0a18a53-d520-4795-9b3b-0f93bcf35848',
    name: 'Eon Frolicker',
    layout: 'normal',
    type_line: 'Creature — Elemental Otter',
    mana_cost: '{2}{U}{U}',
    oracle_text:
      "Flying\nWhen this creature enters, if you cast it, target opponent takes an extra turn after this one. Until your next turn, you and planeswalkers you control gain protection from that player. (You and planeswalkers you control can't be targeted, dealt damage, or enchanted by anything controlled by that player.)",
    keywords: ['Flying'],
    power: '5',
    toughness: '5',
    cmc: 4,
  },
  'Descent into Madness': {
    oracle_id: '88d42e0e-3921-4873-a53b-146220341f76',
    name: 'Descent into Madness',
    layout: 'normal',
    type_line: 'Enchantment',
    mana_cost: '{3}{B}{B}',
    oracle_text:
      'At the beginning of your upkeep, put a despair counter on this enchantment, then each player exiles X permanents they control and/or cards from their hand, where X is the number of despair counters on this enchantment.',
    keywords: [],
    cmc: 5,
  },
  'Oriq Loremage': {
    oracle_id: '7d1dbe80-9ad0-41ad-8ba6-e1094f596eaf',
    name: 'Oriq Loremage',
    layout: 'normal',
    type_line: 'Creature — Human Warlock',
    mana_cost: '{2}{B}{B}',
    oracle_text:
      "{T}: Search your library for a card, put it into your graveyard, then shuffle. If it's an instant or sorcery card, put a +1/+1 counter on this creature.",
    keywords: [],
    power: '3',
    toughness: '3',
    cmc: 4,
  },
  'Higure, the Still Wind': {
    oracle_id: '01197456-62f1-4bc0-9f2f-127f97f9b05d',
    name: 'Higure, the Still Wind',
    layout: 'normal',
    type_line: 'Legendary Creature — Human Ninja',
    mana_cost: '{3}{U}{U}',
    oracle_text:
      "Ninjutsu {2}{U}{U} ({2}{U}{U}, Return an unblocked attacker you control to hand: Put this card onto the battlefield from your hand tapped and attacking.)\nWhenever Higure deals combat damage to a player, you may search your library for a Ninja card, reveal it, put it into your hand, then shuffle.\n{2}: Target Ninja creature can't be blocked this turn.",
    keywords: ['Ninjutsu'],
    power: '3',
    toughness: '4',
    cmc: 5,
  },
  'Scheming Symmetry': {
    oracle_id: '6dfb50d7-359b-4644-90e3-7ecdacee7c12',
    name: 'Scheming Symmetry',
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{B}',
    oracle_text:
      'Choose two target players. Each of them searches their library for a card, then shuffles and puts that card on top.',
    keywords: [],
    cmc: 1,
  },
  'Vexing Puzzlebox': {
    oracle_id: '7267ab16-2157-4b86-93ea-ca2c0fee064a',
    name: 'Vexing Puzzlebox',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{3}',
    oracle_text:
      'Whenever you roll one or more dice, put a number of charge counters on this artifact equal to the result.\n{T}: Add one mana of any color. Roll a d20.\n{T}, Remove 100 charge counters from this artifact: Search your library for an artifact card, put that card onto the battlefield, then shuffle.',
    keywords: [],
    cmc: 3,
  },
  'Teferi, Master of Time': {
    oracle_id: 'e802fb53-7cf5-46bc-8a0b-f99cf5c20f74',
    name: 'Teferi, Master of Time',
    layout: 'normal',
    type_line: 'Legendary Planeswalker — Teferi',
    mana_cost: '{2}{U}{U}',
    oracle_text:
      "You may activate loyalty abilities of Teferi on any player's turn any time you could cast an instant.\n+1: Draw a card, then discard a card.\n−3: Target creature you don't control phases out. (Treat it and anything attached to it as though they don't exist until its controller's next turn.)\n−10: Take two extra turns after this one.",
    keywords: [],
    loyalty: '3',
    cmc: 4,
  },
  'Soul Net': {
    oracle_id: '6021c2d6-d098-4de2-9c7e-4c571f9238f6',
    name: 'Soul Net',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{1}',
    oracle_text: 'Whenever a creature dies, you may pay {1}. If you do, you gain 1 life.',
    keywords: [],
    cmc: 1,
  },
  'Bounty Board': {
    oracle_id: 'e40c66cf-0a4a-4833-98bf-c685d35b9309',
    name: 'Bounty Board',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{3}',
    oracle_text:
      "{T}: Add one mana of any color.\n{1}, {T}: Put a bounty counter on target creature. Activate only as a sorcery.\nWhenever a creature with a bounty counter on it dies, each of its controller's opponents draws a card and gains 2 life.",
    keywords: [],
    cmc: 3,
  },
  'Sanctum of Ugin': {
    oracle_id: '72cb5dcd-9b24-435c-921a-3766108374c4',
    name: 'Sanctum of Ugin',
    layout: 'normal',
    type_line: 'Land',
    mana_cost: '',
    oracle_text:
      '{T}: Add {C}.\nWhenever you cast a colorless spell with mana value 7 or greater, you may sacrifice this land. If you do, search your library for a colorless creature card, reveal it, put it into your hand, then shuffle.',
    keywords: [],
    cmc: 0,
  },
  'Skrelv, Defector Mite': {
    oracle_id: '20053847-6623-493c-8cdb-a69cda3b1577',
    name: 'Skrelv, Defector Mite',
    layout: 'normal',
    type_line: 'Legendary Artifact Creature — Phyrexian Mite',
    mana_cost: '{W}',
    oracle_text:
      "Toxic 1 (Players dealt combat damage by this creature also get a poison counter.)\nSkrelv can't block.\n{W/P}, {T}: Choose a color. Another target creature you control gains toxic 1 and hexproof from that color until end of turn. It can't be blocked by creatures of that color this turn. ({W/P} can be paid with either {W} or 2 life.)",
    keywords: ['Toxic'],
    power: '1',
    toughness: '1',
    cmc: 1,
  },
  'Viscera Seer': {
    oracle_id: 'f82a4e85-526d-4456-b700-7760043a31be',
    name: 'Viscera Seer',
    layout: 'normal',
    type_line: 'Creature — Vampire Wizard',
    mana_cost: '{B}',
    oracle_text:
      'Sacrifice a creature: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)',
    keywords: ['Scry'],
    power: '1',
    toughness: '1',
    cmc: 1,
  },
  'Braidwood Sextant': {
    oracle_id: 'b44816b4-44ef-446d-a254-b4b7bc015a42',
    name: 'Braidwood Sextant',
    layout: 'normal',
    type_line: 'Artifact',
    mana_cost: '{1}',
    oracle_text:
      '{2}, {T}, Sacrifice this artifact: Search your library for a basic land card, reveal that card, put it into your hand, then shuffle.',
    keywords: [],
    cmc: 1,
  },
  'Goblin Matron': {
    oracle_id: '145737a7-c597-4dec-b752-207c2d0501e3',
    name: 'Goblin Matron',
    layout: 'normal',
    type_line: 'Creature — Goblin',
    mana_cost: '{2}{R}',
    oracle_text:
      'When this creature enters, you may search your library for a Goblin card, reveal that card, put it into your hand, then shuffle.',
    keywords: [],
    power: '1',
    toughness: '1',
    cmc: 3,
  },
  Plaguecrafter: {
    oracle_id: '2e3ee458-fa3f-4452-ab95-5a7fb5a0483b',
    name: 'Plaguecrafter',
    layout: 'normal',
    type_line: 'Creature — Human Shaman',
    mana_cost: '{2}{B}',
    oracle_text:
      "When this creature enters, each player sacrifices a creature or planeswalker of their choice. Each player who can't discards a card.",
    keywords: [],
    power: '3',
    toughness: '2',
    cmc: 3,
  },
  'Captain Lannery Storm': {
    oracle_id: '235bf0ba-658c-463f-b112-7478ba27bd7b',
    name: 'Captain Lannery Storm',
    layout: 'normal',
    type_line: 'Legendary Creature — Human Pirate',
    mana_cost: '{2}{R}',
    oracle_text:
      'Haste\nWhenever Captain Lannery Storm attacks, create a Treasure token. (It\'s an artifact with "{T}, Sacrifice this token: Add one mana of any color.")\nWhenever you sacrifice a Treasure, Captain Lannery Storm gets +1/+0 until end of turn.',
    keywords: ['Treasure', 'Haste'],
    power: '2',
    toughness: '2',
    cmc: 3,
  },
  Plummet: {
    oracle_id: '85bde6ac-3dd4-4946-8b57-24f57e3eae2b',
    name: 'Plummet',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{G}',
    oracle_text: 'Destroy target creature with flying.',
    keywords: [],
    cmc: 2,
  },
  "Hero's Demise": {
    oracle_id: '69ec0b59-a0aa-4878-a3b3-130cea18fee0',
    name: "Hero's Demise",
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{B}',
    oracle_text: 'Destroy target legendary creature.',
    keywords: [],
    cmc: 2,
  },
  Murder: {
    oracle_id: '938b4e2c-88d9-4637-bc00-e228920c9a78',
    name: 'Murder',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{B}{B}',
    oracle_text: 'Destroy target creature.',
    keywords: [],
    cmc: 3,
  },
  'Kill Shot': {
    oracle_id: 'e1ce32c7-a882-4d3a-9fd6-e5e2943382fb',
    name: 'Kill Shot',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{2}{W}',
    oracle_text: 'Destroy target attacking creature.',
    keywords: [],
    cmc: 3,
  },
  'Cast Down': {
    oracle_id: 'cdaab6b0-1a2d-4809-8e6b-56013acd8f78',
    name: 'Cast Down',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{B}',
    oracle_text: 'Destroy target nonlegendary creature.',
    keywords: [],
    cmc: 2,
  },
  "Council's Judgment": {
    oracle_id: 'acf4d685-a718-42f7-9a7a-dee069ae8db2',
    name: "Council's Judgment",
    layout: 'normal',
    type_line: 'Sorcery',
    mana_cost: '{1}{W}{W}',
    oracle_text:
      "Will of the council — Starting with you, each player votes for a nonland permanent you don't control. Exile each permanent with the most votes or tied for most votes.",
    keywords: [],
    cmc: 3,
  },
  'Bring Low': {
    oracle_id: 'cfe4d707-41b3-4897-b13a-dcae8f1f3350',
    name: 'Bring Low',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{3}{R}',
    oracle_text:
      'Bring Low deals 3 damage to target creature. If that creature has a +1/+1 counter on it, Bring Low deals 5 damage to it instead.',
    keywords: [],
    cmc: 4,
  },
  'Doom Blade': {
    oracle_id: '59e7f2ae-4535-4191-98be-3e65b6b2befa',
    name: 'Doom Blade',
    layout: 'normal',
    type_line: 'Instant',
    mana_cost: '{1}{B}',
    oracle_text: 'Destroy target nonblack creature.',
    keywords: [],
    cmc: 2,
  },
};
