// E511 coverage table: every tag on EDHREC's theme and typal lists, with the
// strategy vocabulary's ruling for it. Snapshot of 2026-09-29 from
//   https://json.edhrec.com/pages/tags/themes.json (269 tags)
//   https://json.edhrec.com/pages/tags/typal.json (131 tags)
// read from container.json_dict.cardlists[0].cardviews: `name`, the slug at
// the end of `url`, and `num_decks`.
//
// A row names an `archetype` (what the tag builds, via `themeArchetype`) or a
// `ruling` (why the tag names no strategy, `NON_STRATEGY_THEMES`), the synergy
// `axes` that can confirm it in card text (`themeAxes`), and for a typal tag
// the creature `tribe` it resolves to. strategyVocabulary.coverage.test.ts
// holds the vocabulary to this table. To refresh: fetch both lists, add a row
// for every new tag, and give it an entry or a ruling until the test passes.
import type { AxisKey } from '@/deck-builder/services/synergy/axes';
import type { Archetype } from '@/deck-builder/types';
import type { NonStrategyReason } from './strategyVocabulary';

export const EDHREC_TAGS_SNAPSHOT_DATE = '2026-09-29';

export interface EdhrecTagRow {
  name: string;
  slug: string;
  decks: number;
  list: 'themes' | 'typal';
  archetype?: `${Archetype}`;
  ruling?: NonStrategyReason;
  axes: AxisKey[];
  tribe?: string;
}

export const EDHREC_TAGS: EdhrecTagRow[] = [
  {
    name: 'Tokens',
    slug: 'tokens',
    decks: 204323,
    list: 'themes',
    archetype: 'tokens',
    axes: ['tokens'],
  },
  {
    name: '+1/+1 Counters',
    slug: 'plus-1-plus-1-counters',
    decks: 166323,
    list: 'themes',
    archetype: 'midrange',
    axes: ['counters'],
  },
  { name: 'Combo', slug: 'combo', decks: 120273, list: 'themes', archetype: 'combo', axes: [] },
  {
    name: 'Artifacts',
    slug: 'artifacts',
    decks: 117889,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  { name: 'Aggro', slug: 'aggro', decks: 101641, list: 'themes', archetype: 'aggro', axes: [] },
  {
    name: 'Spellslinger',
    slug: 'spellslinger',
    decks: 89003,
    list: 'themes',
    archetype: 'spellslinger',
    axes: ['spellslinger'],
  },
  {
    name: 'Reanimator',
    slug: 'reanimator',
    decks: 85835,
    list: 'themes',
    archetype: 'reanimator',
    axes: ['graveyard'],
  },
  {
    name: 'Lifegain',
    slug: 'lifegain',
    decks: 84530,
    list: 'themes',
    archetype: 'midrange',
    axes: ['lifegain'],
  },
  {
    name: 'Aristocrats',
    slug: 'aristocrats',
    decks: 70965,
    list: 'themes',
    archetype: 'aristocrats',
    axes: ['sacrifice'],
  },
  {
    name: 'Control',
    slug: 'control',
    decks: 70758,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  { name: 'Burn', slug: 'burn', decks: 66422, list: 'themes', archetype: 'aggro', axes: [] },
  {
    name: 'Lands Matter',
    slug: 'lands-matter',
    decks: 65366,
    list: 'themes',
    archetype: 'landfall',
    axes: ['landfall'],
  },
  { name: 'Ramp', slug: 'ramp', decks: 63687, list: 'themes', ruling: 'resource', axes: [] },
  {
    name: 'Voltron',
    slug: 'voltron',
    decks: 59925,
    list: 'themes',
    archetype: 'voltron',
    axes: ['equipment', 'auras'],
  },
  {
    name: 'Equipment',
    slug: 'equipment',
    decks: 57074,
    list: 'themes',
    archetype: 'voltron',
    axes: ['equipment'],
  },
  {
    name: 'Enchantress',
    slug: 'enchantress',
    decks: 56726,
    list: 'themes',
    archetype: 'enchantress',
    axes: ['enchantress'],
  },
  {
    name: 'Midrange',
    slug: 'midrange',
    decks: 54410,
    list: 'themes',
    archetype: 'midrange',
    axes: [],
  },
  {
    name: 'Mill',
    slug: 'mill',
    decks: 49075,
    list: 'themes',
    ruling: 'unmodeled',
    axes: [],
  },
  {
    name: 'Treasure',
    slug: 'treasure',
    decks: 39567,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  {
    name: 'Blink',
    slug: 'blink',
    decks: 37601,
    list: 'themes',
    archetype: 'midrange',
    axes: ['blink'],
  },
  {
    name: 'Sacrifice',
    slug: 'sacrifice',
    decks: 35156,
    list: 'themes',
    archetype: 'aristocrats',
    axes: ['sacrifice'],
  },
  { name: 'Legends', slug: 'legends', decks: 33996, list: 'themes', ruling: 'flavor', axes: [] },
  {
    name: 'Discard',
    slug: 'discard',
    decks: 33922,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['discard'],
  },
  {
    name: 'Graveyard',
    slug: 'graveyard',
    decks: 33504,
    list: 'themes',
    archetype: 'reanimator',
    axes: ['graveyard'],
  },
  {
    name: 'Auras',
    slug: 'auras',
    decks: 32678,
    list: 'themes',
    archetype: 'voltron',
    axes: ['auras'],
  },
  { name: 'Clones', slug: 'clones', decks: 31117, list: 'themes', archetype: 'midrange', axes: [] },
  {
    name: 'Wheels',
    slug: 'wheels',
    decks: 29476,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  {
    name: 'Card Draw',
    slug: 'card-draw',
    decks: 28283,
    list: 'themes',
    ruling: 'resource',
    axes: [],
  },
  { name: 'Flying', slug: 'flying', decks: 28277, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Group Slug',
    slug: 'group-slug',
    decks: 24758,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  { name: 'Historic', slug: 'historic', decks: 24240, list: 'themes', ruling: 'flavor', axes: [] },
  {
    name: 'Landfall',
    slug: 'landfall',
    decks: 23505,
    list: 'themes',
    archetype: 'landfall',
    axes: ['landfall'],
  },
  { name: 'Storm', slug: 'storm', decks: 23359, list: 'themes', archetype: 'storm', axes: [] },
  { name: 'Stax', slug: 'stax', decks: 22960, list: 'themes', archetype: 'control', axes: [] },
  {
    name: 'Self-Mill',
    slug: 'self-mill',
    decks: 22045,
    list: 'themes',
    archetype: 'reanimator',
    axes: ['graveyard'],
  },
  { name: 'Theft', slug: 'theft', decks: 21394, list: 'themes', archetype: 'goodstuff', axes: [] },
  {
    name: 'Extra Combats',
    slug: 'extra-combats',
    decks: 21185,
    list: 'themes',
    archetype: 'aggro',
    axes: [],
  },
  {
    name: 'Infect',
    slug: 'infect',
    decks: 21122,
    list: 'themes',
    archetype: 'aggro',
    axes: ['poison'],
  },
  {
    name: 'Good Stuff',
    slug: 'good-stuff',
    decks: 20208,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  {
    name: 'Group Hug',
    slug: 'group-hug',
    decks: 20180,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['grouphug'],
  },
  { name: 'Big Mana', slug: 'big-mana', decks: 19889, list: 'themes', ruling: 'flavor', axes: [] },
  {
    name: 'Forced Combat',
    slug: 'forced-combat',
    decks: 16790,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  { name: 'Chaos', slug: 'chaos', decks: 16327, list: 'themes', archetype: 'goodstuff', axes: [] },
  {
    name: 'Commander Matters',
    slug: 'commander-matters',
    decks: 15799,
    list: 'themes',
    ruling: 'flavor',
    axes: [],
  },
  {
    name: 'Planeswalkers',
    slug: 'planeswalkers',
    decks: 15631,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['superfriends'],
  },
  {
    name: 'Vehicles',
    slug: 'vehicles',
    decks: 15538,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['vehicles'],
  },
  { name: 'X Spells', slug: 'x-spells', decks: 15531, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Toolbox',
    slug: 'toolbox',
    decks: 13942,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  {
    name: 'Lifedrain',
    slug: 'lifedrain',
    decks: 13887,
    list: 'themes',
    archetype: 'aristocrats',
    axes: [],
  },
  {
    name: 'Birthing Pod',
    slug: 'birthing-pod',
    decks: 13435,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: '-1/-1 Counters',
    slug: 'minus-1-minus-1-counters',
    decks: 13053,
    list: 'themes',
    archetype: 'midrange',
    axes: [],
  },
  {
    name: 'Cascade',
    slug: 'cascade',
    decks: 12997,
    list: 'themes',
    archetype: 'midrange',
    axes: [],
  },
  {
    name: 'Pillow Fort',
    slug: 'pillow-fort',
    decks: 12912,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  { name: 'Exile', slug: 'exile', decks: 12311, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Tempo', slug: 'tempo', decks: 11960, list: 'themes', archetype: 'tempo', axes: [] },
  {
    name: 'Hatebears',
    slug: 'hatebears',
    decks: 11857,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  {
    name: 'Cantrips',
    slug: 'cantrips',
    decks: 10756,
    list: 'themes',
    archetype: 'spellslinger',
    axes: ['spellslinger'],
  },
  {
    name: 'Extra Turns',
    slug: 'extra-turns',
    decks: 10745,
    list: 'themes',
    archetype: 'combo',
    axes: [],
  },
  {
    name: 'Dredge',
    slug: 'dredge',
    decks: 10699,
    list: 'themes',
    archetype: 'reanimator',
    axes: ['graveyard'],
  },
  { name: 'Stompy', slug: 'stompy', decks: 10627, list: 'themes', archetype: 'aggro', axes: [] },
  {
    name: 'ETB',
    slug: 'etb',
    decks: 10360,
    list: 'themes',
    archetype: 'midrange',
    axes: ['blink'],
  },
  {
    name: 'Populate',
    slug: 'populate',
    decks: 10132,
    list: 'themes',
    archetype: 'tokens',
    axes: ['tokens'],
  },
  {
    name: 'Self-Damage',
    slug: 'self-damage',
    decks: 10006,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Spell Copy',
    slug: 'spell-copy',
    decks: 10002,
    list: 'themes',
    archetype: 'spellslinger',
    axes: ['spellslinger'],
  },
  {
    name: 'Toughness Matters',
    slug: 'toughness-matters',
    decks: 9589,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Topdeck', slug: 'topdeck', decks: 9515, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Proliferate',
    slug: 'proliferate',
    decks: 9460,
    list: 'themes',
    archetype: 'midrange',
    axes: [],
  },
  {
    name: 'Energy',
    slug: 'energy',
    decks: 8529,
    list: 'themes',
    archetype: 'midrange',
    axes: ['energy'],
  },
  {
    name: 'Attack Triggers',
    slug: 'attack-triggers',
    decks: 8007,
    list: 'themes',
    archetype: 'aggro',
    axes: [],
  },
  {
    name: 'Land Destruction',
    slug: 'land-destruction',
    decks: 7814,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  {
    name: 'Affinity',
    slug: 'affinity',
    decks: 7709,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  { name: 'Ninjutsu', slug: 'ninjutsu', decks: 7460, list: 'themes', archetype: 'tempo', axes: [] },
  {
    name: 'Food',
    slug: 'food',
    decks: 7418,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  { name: 'Sagas', slug: 'sagas', decks: 7197, list: 'themes', archetype: 'enchantress', axes: [] },
  {
    name: 'Defenders',
    slug: 'defenders',
    decks: 6703,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Monarch',
    slug: 'monarch',
    decks: 6362,
    list: 'themes',
    archetype: 'midrange',
    axes: ['monarch'],
  },
  {
    name: 'Cycling',
    slug: 'cycling',
    decks: 6011,
    list: 'themes',
    archetype: 'midrange',
    axes: ['cycling'],
  },
  { name: 'Morph', slug: 'morph', decks: 5853, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Clues',
    slug: 'clues',
    decks: 5640,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  { name: 'Anthems', slug: 'anthems', decks: 5534, list: 'themes', archetype: 'tokens', axes: [] },
  {
    name: 'Modified Creatures',
    slug: 'modified-creatures',
    decks: 5523,
    list: 'themes',
    archetype: 'voltron',
    axes: [],
  },
  {
    name: 'Counterspells',
    slug: 'counterspells',
    decks: 5497,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  {
    name: 'Activated Abilities',
    slug: 'activated-abilities',
    decks: 5436,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Tap / Untap',
    slug: 'tap-untap',
    decks: 5335,
    list: 'themes',
    archetype: 'combo',
    axes: [],
  },
  { name: 'Pingers', slug: 'pingers', decks: 5183, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Devotion', slug: 'devotion', decks: 5095, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Deathtouch',
    slug: 'deathtouch',
    decks: 5059,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Politics',
    slug: 'politics',
    decks: 4920,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  { name: 'Snow', slug: 'snow', decks: 4763, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Unblockable',
    slug: 'unblockable',
    decks: 4631,
    list: 'themes',
    archetype: 'tempo',
    axes: [],
  },
  {
    name: 'Triggered Abilities',
    slug: 'triggered-abilities',
    decks: 4492,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Unnatural',
    slug: 'unnatural',
    decks: 4492,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Mutate', slug: 'mutate', decks: 4483, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Dungeon',
    slug: 'dungeon',
    decks: 4478,
    list: 'themes',
    archetype: 'midrange',
    axes: ['venture'],
  },
  {
    name: 'Discover',
    slug: 'discover',
    decks: 4431,
    list: 'themes',
    archetype: 'midrange',
    axes: [],
  },
  { name: 'Zoo', slug: 'zoo', decks: 4403, list: 'themes', archetype: 'aggro', axes: [] },
  {
    name: 'Ad Nauseam',
    slug: 'ad-nauseam',
    decks: 4258,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Flashback',
    slug: 'flashback',
    decks: 4200,
    list: 'themes',
    archetype: 'reanimator',
    axes: ['graveyard'],
  },
  { name: 'Flash', slug: 'flash', decks: 4002, list: 'themes', archetype: 'control', axes: [] },
  { name: 'Fight', slug: 'fight', decks: 3850, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Prowess',
    slug: 'prowess',
    decks: 3818,
    list: 'themes',
    archetype: 'spellslinger',
    axes: ['spellslinger'],
  },
  { name: 'Donate', slug: 'donate', decks: 3507, list: 'themes', archetype: 'goodstuff', axes: [] },
  {
    name: 'Self-Discard',
    slug: 'self-discard',
    decks: 3346,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['discard'],
  },
  {
    name: 'Counters Matter',
    slug: 'counters-matter',
    decks: 3202,
    list: 'themes',
    archetype: 'midrange',
    axes: ['counters'],
  },
  { name: 'Aikido', slug: 'aikido', decks: 3096, list: 'themes', archetype: 'control', axes: [] },
  { name: 'Eggs', slug: 'eggs', decks: 3070, list: 'themes', archetype: 'combo', axes: [] },
  { name: 'Haste', slug: 'haste', decks: 2938, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Sea Creatures',
    slug: 'sea-creatures',
    decks: 2851,
    list: 'themes',
    archetype: 'tribal',
    axes: ['tribal'],
  },
  {
    name: 'Rat Colony',
    slug: 'rat-colony',
    decks: 2799,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  { name: 'Bounce', slug: 'bounce', decks: 2789, list: 'themes', archetype: 'tempo', axes: [] },
  { name: 'Power', slug: 'power', decks: 2731, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Prison', slug: 'prison', decks: 2715, list: 'themes', archetype: 'control', axes: [] },
  {
    name: 'Multicolor Matters',
    slug: 'multicolor-matters',
    decks: 2432,
    list: 'themes',
    ruling: 'flavor',
    axes: [],
  },
  {
    name: 'Impulse Draw',
    slug: 'impulse-draw',
    decks: 2406,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Earthbending',
    slug: 'earthbending',
    decks: 2284,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Coin Flip',
    slug: 'coin-flip',
    decks: 2247,
    list: 'themes',
    archetype: 'goodstuff',
    axes: [],
  },
  { name: 'Keywords', slug: 'keywords', decks: 2210, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Party',
    slug: 'party',
    decks: 2183,
    list: 'themes',
    archetype: 'tribal',
    axes: ['tribal'],
  },
  { name: 'Scry', slug: 'scry', decks: 2165, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: "Dragon's Approach",
    slug: 'dragons-approach',
    decks: 2151,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Modular',
    slug: 'modular',
    decks: 2036,
    list: 'themes',
    archetype: 'artifacts',
    axes: [],
  },
  {
    name: 'Amass',
    slug: 'amass',
    decks: 1987,
    list: 'themes',
    archetype: 'tokens',
    axes: ['tokens'],
  },
  {
    name: 'Guildgates',
    slug: 'guildgates',
    decks: 1972,
    list: 'themes',
    archetype: 'landfall',
    axes: [],
  },
  { name: 'Foretell', slug: 'foretell', decks: 1935, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Rock', slug: 'rock', decks: 1897, list: 'themes', archetype: 'midrange', axes: [] },
  {
    name: 'Curses',
    slug: 'curses',
    decks: 1857,
    list: 'themes',
    archetype: 'enchantress',
    axes: [],
  },
  {
    name: 'Sunforger',
    slug: 'sunforger',
    decks: 1841,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Power Matters',
    slug: 'power-matters',
    decks: 1756,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Die Roll',
    slug: 'die-roll',
    decks: 1755,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['dice'],
  },
  { name: 'Weenies', slug: 'weenies', decks: 1718, list: 'themes', archetype: 'aggro', axes: [] },
  { name: 'Cheerios', slug: 'cheerios', decks: 1643, list: 'themes', archetype: 'combo', axes: [] },
  { name: 'Tron', slug: 'tron', decks: 1638, list: 'themes', ruling: 'package', axes: [] },
  { name: 'The Ring', slug: 'the-ring', decks: 1548, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Land Animation',
    slug: 'land-animation',
    decks: 1527,
    list: 'themes',
    archetype: 'landfall',
    axes: [],
  },
  { name: 'Fling', slug: 'fling', decks: 1513, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Shadowborn Apostles',
    slug: 'shadowborn-apostles',
    decks: 1421,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Madness',
    slug: 'madness',
    decks: 1409,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['discard'],
  },
  {
    name: 'Persistent Petitioners',
    slug: 'persistent-petitioners',
    decks: 1406,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Attractions',
    slug: 'attractions',
    decks: 1399,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Convoke',
    slug: 'convoke',
    decks: 1396,
    list: 'themes',
    archetype: 'tokens',
    axes: ['tokens'],
  },
  {
    name: 'Experience Counters',
    slug: 'experience-counters',
    decks: 1393,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Firebending',
    slug: 'firebending',
    decks: 1358,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Surveil',
    slug: 'surveil',
    decks: 1310,
    list: 'themes',
    archetype: 'reanimator',
    axes: ['graveyard'],
  },
  { name: 'Connive', slug: 'connive', decks: 1298, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Polymorph',
    slug: 'polymorph',
    decks: 1287,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Devoid', slug: 'devoid', decks: 1240, list: 'themes', ruling: 'flavor', axes: [] },
  {
    name: 'Annihilator',
    slug: 'annihilator',
    decks: 1209,
    list: 'themes',
    ruling: 'flavor',
    axes: [],
  },
  {
    name: 'Shrines',
    slug: 'shrines',
    decks: 1205,
    list: 'themes',
    archetype: 'enchantress',
    axes: [],
  },
  {
    name: 'Sneak Attack',
    slug: 'sneak-attack',
    decks: 1187,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Glass Cannon',
    slug: 'glass-cannon',
    decks: 1133,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Crime', slug: 'crime', decks: 1119, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Charge Counters',
    slug: 'charge-counters',
    decks: 1118,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Rad Counters',
    slug: 'rad-counters',
    decks: 1115,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Suspend', slug: 'suspend', decks: 1113, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Explore', slug: 'explore', decks: 1096, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Blood',
    slug: 'blood',
    decks: 1091,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  {
    name: 'Outlaws',
    slug: 'outlaws',
    decks: 1091,
    list: 'themes',
    archetype: 'tribal',
    axes: ['tribal'],
  },
  {
    name: 'Primal Surge',
    slug: 'primal-surge',
    decks: 1084,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  { name: 'Myriad', slug: 'myriad', decks: 1012, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Adventures',
    slug: 'adventures',
    decks: 993,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Deserts', slug: 'deserts', decks: 976, list: 'themes', archetype: 'landfall', axes: [] },
  {
    name: 'Time Counters',
    slug: 'time-counters',
    decks: 968,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Delver', slug: 'delver', decks: 965, list: 'themes', ruling: 'package', axes: [] },
  {
    name: 'Kaheera Companion',
    slug: 'kaheera-companion',
    decks: 962,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  { name: 'Hand Size', slug: 'hand-size', decks: 922, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Extra Upkeeps',
    slug: 'extra-upkeeps',
    decks: 891,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Looting',
    slug: 'looting',
    decks: 889,
    list: 'themes',
    archetype: 'goodstuff',
    axes: ['discard'],
  },
  { name: 'Enrage', slug: 'enrage', decks: 882, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Lessons', slug: 'lessons', decks: 853, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Life Exchange',
    slug: 'life-exchange',
    decks: 849,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Airbending',
    slug: 'airbending',
    decks: 790,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Slime Against Humanity',
    slug: 'slime-against-humanity',
    decks: 785,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Relentless Rats',
    slug: 'relentless-rats',
    decks: 754,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Indestructible',
    slug: 'indestructible',
    decks: 743,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Exalted', slug: 'exalted', decks: 691, list: 'themes', archetype: 'voltron', axes: [] },
  {
    name: 'Hare Apparent',
    slug: 'hare-apparent',
    decks: 634,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  { name: 'Rooms', slug: 'rooms', decks: 616, list: 'themes', archetype: 'enchantress', axes: [] },
  { name: 'Evoke', slug: 'evoke', decks: 606, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Waterbending',
    slug: 'waterbending',
    decks: 592,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Freerunning',
    slug: 'freerunning',
    decks: 571,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Mana Dorks',
    slug: 'mana-dorks',
    decks: 565,
    list: 'themes',
    ruling: 'resource',
    axes: [],
  },
  { name: 'Vanilla', slug: 'vanilla', decks: 558, list: 'themes', ruling: 'flavor', axes: [] },
  {
    name: 'Creatureless',
    slug: 'creatureless',
    decks: 509,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  { name: 'Transform', slug: 'transform', decks: 502, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Blue Moon', slug: 'blue-moon', decks: 476, list: 'themes', ruling: 'package', axes: [] },
  { name: 'Landwalk', slug: 'landwalk', decks: 472, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Speed', slug: 'speed', decks: 472, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Stoneblade',
    slug: 'stoneblade',
    decks: 471,
    list: 'themes',
    archetype: 'voltron',
    axes: ['equipment'],
  },
  {
    name: 'Keruga Companion',
    slug: 'keruga-companion',
    decks: 459,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Villainous Choice',
    slug: 'villainous-choice',
    decks: 458,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Voting', slug: 'voting', decks: 451, list: 'themes', archetype: 'goodstuff', axes: [] },
  {
    name: 'Jegantha Companion',
    slug: 'jegantha-companion',
    decks: 449,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Old School',
    slug: 'old-school',
    decks: 442,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'LTB Effects',
    slug: 'ltb-effects',
    decks: 436,
    list: 'themes',
    archetype: 'midrange',
    axes: [],
  },
  {
    name: 'Delirium',
    slug: 'delirium',
    decks: 426,
    list: 'themes',
    archetype: 'reanimator',
    axes: [],
  },
  {
    name: 'Turbo Fog',
    slug: 'turbo-fog',
    decks: 415,
    list: 'themes',
    archetype: 'control',
    axes: [],
  },
  {
    name: 'Obosh Companion',
    slug: 'obosh-companion',
    decks: 412,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  { name: 'Reach', slug: 'reach', decks: 398, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Offspring',
    slug: 'offspring',
    decks: 388,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  {
    name: 'Color Hack',
    slug: 'color-hack',
    decks: 385,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Saboteurs',
    slug: 'saboteurs',
    decks: 379,
    list: 'themes',
    archetype: 'aggro',
    axes: [],
  },
  {
    name: 'Spore Counters',
    slug: 'spore-counters',
    decks: 374,
    list: 'themes',
    archetype: 'tokens',
    axes: [],
  },
  { name: 'Type Hack', slug: 'type-hack', decks: 342, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Day / Night',
    slug: 'day-night',
    decks: 327,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Warp', slug: 'warp', decks: 304, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Umori Companion',
    slug: 'umori-companion',
    decks: 297,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Self-Destruct',
    slug: 'self-destruct',
    decks: 296,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Lure', slug: 'lure', decks: 288, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Heroic', slug: 'heroic', decks: 279, list: 'themes', archetype: 'voltron', axes: [] },
  { name: 'Mayhem', slug: 'mayhem', decks: 271, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Lurrus Companion',
    slug: 'lurrus-companion',
    decks: 271,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  { name: 'Sneak', slug: 'sneak', decks: 270, list: 'themes', archetype: 'tempo', axes: [] },
  { name: 'Plot', slug: 'plot', decks: 265, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Stun', slug: 'stun', decks: 264, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Rube Goldberg',
    slug: 'rube-goldberg',
    decks: 258,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Turbo', slug: 'turbo', decks: 256, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Paradox', slug: 'paradox', decks: 254, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Battles', slug: 'battles', decks: 239, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Banding', slug: 'banding', decks: 238, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Hellbent', slug: 'hellbent', decks: 237, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Phasing', slug: 'phasing', decks: 232, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Descend',
    slug: 'descend',
    decks: 223,
    list: 'themes',
    archetype: 'reanimator',
    axes: [],
  },
  {
    name: 'Web-slinging',
    slug: 'web-slinging',
    decks: 211,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Towns', slug: 'towns', decks: 207, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'All Spells',
    slug: 'all-spells',
    decks: 202,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Kicker', slug: 'kicker', decks: 200, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Skulk', slug: 'skulk', decks: 186, list: 'themes', ruling: 'keyword', axes: [] },
  {
    name: 'Improvise',
    slug: 'improvise',
    decks: 181,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  {
    name: 'Gyruda Companion',
    slug: 'gyruda-companion',
    decks: 165,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Mana Rocks',
    slug: 'mana-rocks',
    decks: 164,
    list: 'themes',
    ruling: 'resource',
    axes: [],
  },
  {
    name: 'Tempest Hawk',
    slug: 'tempest-hawk',
    decks: 154,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  {
    name: 'Oil Counters',
    slug: 'oil-counters',
    decks: 146,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  {
    name: 'Bobbleheads',
    slug: 'bobbleheads',
    decks: 145,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Miracles', slug: 'miracle', decks: 135, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Stickers', slug: 'stickers', decks: 127, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Summons', slug: 'summons', decks: 120, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Incubate',
    slug: 'incubate',
    decks: 113,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  {
    name: 'Templar Knights',
    slug: 'templar-knights',
    decks: 111,
    list: 'themes',
    ruling: 'package',
    axes: [],
  },
  { name: 'Menace', slug: 'menace', decks: 103, list: 'themes', ruling: 'keyword', axes: [] },
  { name: 'Doomsday', slug: 'doomsday', decks: 98, list: 'themes', archetype: 'combo', axes: [] },
  {
    name: 'Bloodthirst',
    slug: 'bloodthirst',
    decks: 91,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Craft', slug: 'craft', decks: 88, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Clash', slug: 'clash', decks: 87, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Sunburst', slug: 'sunburst', decks: 87, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Zirda Companion',
    slug: 'zirda-companion',
    decks: 83,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Exploit',
    slug: 'exploit',
    decks: 81,
    list: 'themes',
    archetype: 'aristocrats',
    axes: [],
  },
  {
    name: 'Servos',
    slug: 'servos',
    decks: 55,
    list: 'themes',
    archetype: 'artifacts',
    axes: ['artifacts'],
  },
  { name: 'Caves', slug: 'caves', decks: 52, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Horsemanship',
    slug: 'horsemanship',
    decks: 50,
    list: 'themes',
    ruling: 'keyword',
    axes: [],
  },
  { name: 'Squad', slug: 'squad', decks: 46, list: 'themes', archetype: 'tokens', axes: [] },
  { name: 'Repartee', slug: 'repartee', decks: 37, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Custom Cards',
    slug: 'custom-cards',
    decks: 35,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Job Select',
    slug: 'job-select',
    decks: 29,
    list: 'themes',
    ruling: 'mechanic',
    axes: [],
  },
  { name: 'Kavu', slug: 'kavu', decks: 29, list: 'themes', archetype: 'tribal', axes: ['tribal'] },
  { name: 'Paradigm', slug: 'paradigm', decks: 26, list: 'themes', ruling: 'format', axes: [] },
  { name: 'Cid', slug: 'cid', decks: 24, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Hippos',
    slug: 'hippos',
    decks: 24,
    list: 'themes',
    archetype: 'tribal',
    axes: ['tribal'],
  },
  { name: 'Premodern', slug: 'premodern', decks: 24, list: 'themes', ruling: 'format', axes: [] },
  { name: 'Level Up', slug: 'level-up', decks: 21, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Retrace', slug: 'retrace', decks: 19, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Books', slug: 'books', decks: 14, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Toys', slug: 'toys', decks: 14, list: 'themes', archetype: 'tribal', axes: ['tribal'] },
  { name: 'Increment', slug: 'increment', decks: 12, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Opus', slug: 'opus', decks: 9, list: 'themes', ruling: 'mechanic', axes: [] },
  {
    name: 'Value Vintage',
    slug: 'value-vintage',
    decks: 9,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  { name: 'Dash', slug: 'dash', decks: 7, list: 'themes', ruling: 'mechanic', axes: [] },
  { name: 'Planechase', slug: 'planechase', decks: 7, list: 'themes', ruling: 'format', axes: [] },
  { name: 'Dandan', slug: 'dandan', decks: 6, list: 'themes', ruling: 'package', axes: [] },
  {
    name: 'European Highlander',
    slug: 'european-highlander',
    decks: 6,
    list: 'themes',
    ruling: 'format',
    axes: [],
  },
  {
    name: 'Dragons',
    slug: 'dragons',
    decks: 22866,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Dragon',
  },
  {
    name: 'Elves',
    slug: 'elves',
    decks: 18329,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Elf',
  },
  {
    name: 'Zombies',
    slug: 'zombies',
    decks: 17069,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Zombie',
  },
  {
    name: 'Vampires',
    slug: 'vampires',
    decks: 14223,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Vampire',
  },
  {
    name: 'Humans',
    slug: 'humans',
    decks: 13793,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Human',
  },
  {
    name: 'Angels',
    slug: 'angels',
    decks: 11671,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Angel',
  },
  {
    name: 'Goblins',
    slug: 'goblins',
    decks: 11387,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Goblin',
  },
  {
    name: 'Eldrazi',
    slug: 'eldrazi',
    decks: 11254,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Eldrazi',
  },
  {
    name: 'Dinosaurs',
    slug: 'dinosaurs',
    decks: 10165,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Dinosaur',
  },
  {
    name: 'Wizards',
    slug: 'wizards',
    decks: 7744,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Wizard',
  },
  {
    name: 'Demons',
    slug: 'demons',
    decks: 6203,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Demon',
  },
  {
    name: 'Cats',
    slug: 'cats',
    decks: 6116,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Cat',
  },
  {
    name: 'Pirates',
    slug: 'pirates',
    decks: 6108,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Pirate',
  },
  {
    name: 'Faeries',
    slug: 'faeries',
    decks: 5613,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Faerie',
  },
  {
    name: 'Merfolk',
    slug: 'merfolk',
    decks: 5462,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Merfolk',
  },
  {
    name: 'Slivers',
    slug: 'slivers',
    decks: 4994,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Sliver',
  },
  {
    name: 'Knights',
    slug: 'knights',
    decks: 4867,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Knight',
  },
  {
    name: 'Phyrexians',
    slug: 'phyrexians',
    decks: 4828,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Phyrexian',
  },
  {
    name: 'Assassins',
    slug: 'assassins',
    decks: 4681,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Assassin',
  },
  {
    name: 'Rats',
    slug: 'rats',
    decks: 4546,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Rat',
  },
  {
    name: 'Birds',
    slug: 'birds',
    decks: 3996,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Bird',
  },
  {
    name: 'Spirits',
    slug: 'spirits',
    decks: 3929,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Spirit',
  },
  {
    name: 'Elementals',
    slug: 'elementals',
    decks: 3881,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Elemental',
  },
  {
    name: 'Ninjas',
    slug: 'ninjas',
    decks: 3852,
    list: 'typal',
    archetype: 'tempo',
    axes: [],
    tribe: 'Ninja',
  },
  {
    name: 'Hydras',
    slug: 'hydras',
    decks: 3846,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Hydra',
  },
  {
    name: 'Soldiers',
    slug: 'soldiers',
    decks: 3729,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Soldier',
  },
  {
    name: 'Horrors',
    slug: 'horrors',
    decks: 3383,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Horror',
  },
  {
    name: 'Saprolings',
    slug: 'saprolings',
    decks: 3212,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Saproling',
  },
  {
    name: 'Warriors',
    slug: 'warriors',
    decks: 3091,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Warrior',
  },
  {
    name: 'Shapeshifters',
    slug: 'shapeshifters',
    decks: 3050,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Shapeshifter',
  },
  {
    name: 'Allies',
    slug: 'allies',
    decks: 2715,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Ally',
  },
  {
    name: 'Squirrels',
    slug: 'squirrels',
    decks: 2672,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Squirrel',
  },
  {
    name: 'Insects',
    slug: 'insects',
    decks: 2664,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Insect',
  },
  {
    name: 'Spiders',
    slug: 'spiders',
    decks: 2550,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Spider',
  },
  {
    name: 'Frogs',
    slug: 'frogs',
    decks: 2436,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Frog',
  },
  {
    name: 'Rogues',
    slug: 'rogues',
    decks: 2374,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Rogue',
  },
  {
    name: 'Dwarves',
    slug: 'dwarves',
    decks: 2296,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Dwarf',
  },
  {
    name: 'Myr',
    slug: 'myr',
    decks: 2206,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Myr',
  },
  {
    name: 'Mutants',
    slug: 'mutants',
    decks: 2049,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Mutant',
  },
  {
    name: 'Clerics',
    slug: 'clerics',
    decks: 1924,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Cleric',
  },
  {
    name: 'Dogs',
    slug: 'dogs',
    decks: 1912,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Dog',
  },
  {
    name: 'Rabbits',
    slug: 'rabbits',
    decks: 1912,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Rabbit',
  },
  {
    name: 'Bears',
    slug: 'bears',
    decks: 1901,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Bear',
  },
  {
    name: 'Werewolves',
    slug: 'werewolves',
    decks: 1869,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Werewolf',
  },
  {
    name: 'Snakes',
    slug: 'snakes',
    decks: 1832,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Snake',
  },
  {
    name: 'Beasts',
    slug: 'beasts',
    decks: 1755,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Beast',
  },
  {
    name: 'Wolves',
    slug: 'wolves',
    decks: 1711,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Wolf',
  },
  {
    name: 'Gods',
    slug: 'gods',
    decks: 1631,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'God',
  },
  {
    name: 'Wraiths',
    slug: 'wraiths',
    decks: 1474,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Wraith',
  },
  {
    name: 'Treefolk',
    slug: 'treefolk',
    decks: 1367,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Treefolk',
  },
  {
    name: 'Heroes',
    slug: 'heroes',
    decks: 1329,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Hero',
  },
  {
    name: 'Otters',
    slug: 'otters',
    decks: 1306,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Otter',
  },
  {
    name: 'Artificers',
    slug: 'artificers',
    decks: 1304,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Artificer',
  },
  {
    name: 'Villains',
    slug: 'villains',
    decks: 1146,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Villain',
  },
  {
    name: 'Halflings',
    slug: 'halflings',
    decks: 1108,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Halfling',
  },
  {
    name: 'Orcs',
    slug: 'orcs',
    decks: 1108,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Orc',
  },
  {
    name: 'Fungi',
    slug: 'fungi',
    decks: 1101,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Fungus',
  },
  {
    name: 'Oozes',
    slug: 'oozes',
    decks: 1091,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Ooze',
  },
  {
    name: 'Thopters',
    slug: 'thopters',
    decks: 1030,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Thopter',
  },
  {
    name: 'Giants',
    slug: 'giants',
    decks: 986,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Giant',
  },
  {
    name: 'Samurai',
    slug: 'samurai',
    decks: 982,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Samurai',
  },
  {
    name: 'Lizards',
    slug: 'lizards',
    decks: 968,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Lizard',
  },
  {
    name: 'Tyranids',
    slug: 'tyranids',
    decks: 964,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Tyranid',
  },
  {
    name: 'Constructs',
    slug: 'constructs',
    decks: 928,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Construct',
  },
  {
    name: 'Bats',
    slug: 'bats',
    decks: 919,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Bat',
  },
  {
    name: 'Sphinxes',
    slug: 'sphinxes',
    decks: 881,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Sphinx',
  },
  {
    name: 'Mice',
    slug: 'mice',
    decks: 879,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Mouse',
  },
  {
    name: 'Apes',
    slug: 'apes',
    decks: 857,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Ape',
  },
  {
    name: 'Golems',
    slug: 'golems',
    decks: 855,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Golem',
  },
  {
    name: 'Wurms',
    slug: 'wurms',
    decks: 848,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Wurm',
  },
  {
    name: 'Robots',
    slug: 'robots',
    decks: 807,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Robot',
  },
  {
    name: 'Spacecraft',
    slug: 'spacecraft',
    decks: 768,
    list: 'typal',
    archetype: 'artifacts',
    axes: [],
  },
  {
    name: 'Scarecrows',
    slug: 'scarecrows',
    decks: 711,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Scarecrow',
  },
  {
    name: 'Raccoons',
    slug: 'raccoons',
    decks: 659,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Raccoon',
  },
  {
    name: 'Skeletons',
    slug: 'skeletons',
    decks: 645,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Skeleton',
  },
  {
    name: 'Minotaurs',
    slug: 'minotaurs',
    decks: 576,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Minotaur',
  },
  {
    name: 'Turtles',
    slug: 'turtles',
    decks: 563,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Turtle',
  },
  {
    name: 'Necrons',
    slug: 'necrons',
    decks: 556,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Necron',
  },
  {
    name: 'Monks',
    slug: 'monks',
    decks: 528,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Monk',
  },
  {
    name: 'Devils',
    slug: 'devils',
    decks: 522,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Devil',
  },
  {
    name: 'Lhurgoyfs',
    slug: 'lhurgoyfs',
    decks: 509,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Lhurgoyf',
  },
  {
    name: 'Time Lords',
    slug: 'time-lords',
    decks: 504,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Time Lord',
  },
  {
    name: 'Druids',
    slug: 'druids',
    decks: 482,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Druid',
  },
  {
    name: 'Monkeys',
    slug: 'monkeys',
    decks: 431,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Monkey',
  },
  {
    name: 'Crabs',
    slug: 'crabs',
    decks: 424,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Crab',
  },
  {
    name: 'Plants',
    slug: 'plants',
    decks: 397,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Plant',
  },
  {
    name: 'Illusions',
    slug: 'illusions',
    decks: 388,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Illusion',
  },
  {
    name: 'Phoenixes',
    slug: 'phoenixes',
    decks: 354,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Phoenix',
  },
  {
    name: 'Nightmares',
    slug: 'nightmares',
    decks: 346,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Nightmare',
  },
  {
    name: 'Mounts',
    slug: 'mounts',
    decks: 343,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Mount',
  },
  {
    name: 'Horses',
    slug: 'horses',
    decks: 336,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Horse',
  },
  {
    name: 'Praetors',
    slug: 'praetors',
    decks: 313,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Praetor',
  },
  {
    name: 'Unicorns',
    slug: 'unicorns',
    decks: 312,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Unicorn',
  },
  {
    name: 'Advisors',
    slug: 'advisors',
    decks: 302,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Advisor',
  },
  {
    name: 'Archers',
    slug: 'archers',
    decks: 299,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Archer',
  },
  {
    name: 'Avatars',
    slug: 'avatars',
    decks: 283,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Avatar',
  },
  {
    name: 'Kithkin',
    slug: 'kithkin',
    decks: 280,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Kithkin',
  },
  {
    name: 'Detectives',
    slug: 'detectives',
    decks: 244,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Detective',
  },
  {
    name: 'Daleks',
    slug: 'daleks',
    decks: 232,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Dalek',
  },
  {
    name: 'Arcane',
    slug: 'arcane',
    decks: 231,
    list: 'typal',
    archetype: 'spellslinger',
    axes: [],
  },
  {
    name: 'Rebels',
    slug: 'rebels',
    decks: 224,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Rebel',
  },
  {
    name: 'Gorgons',
    slug: 'gorgons',
    decks: 185,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Gorgon',
  },
  {
    name: 'Drakes',
    slug: 'drakes',
    decks: 179,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Drake',
  },
  {
    name: 'Cybermen',
    slug: 'cybermen',
    decks: 171,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Cyberman',
  },
  {
    name: 'Astartes',
    slug: 'astartes',
    decks: 166,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Astartes',
  },
  {
    name: 'Griffins',
    slug: 'griffins',
    decks: 163,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Griffin',
  },
  {
    name: 'Gnomes',
    slug: 'gnomes',
    decks: 158,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Gnome',
  },
  {
    name: 'Satyrs',
    slug: 'satyrs',
    decks: 153,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Satyr',
  },
  {
    name: 'Shamans',
    slug: 'shamans',
    decks: 151,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Shaman',
  },
  {
    name: 'Foxes',
    slug: 'foxes',
    decks: 147,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Fox',
  },
  {
    name: 'Moonfolk',
    slug: 'moonfolk',
    decks: 141,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Moonfolk',
  },
  {
    name: 'Atogs',
    slug: 'atogs',
    decks: 128,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Atog',
  },
  {
    name: 'Mercenaries',
    slug: 'mercenaries',
    decks: 111,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Mercenary',
  },
  {
    name: 'Whales',
    slug: 'whales',
    decks: 111,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Whale',
  },
  {
    name: 'Pegasi',
    slug: 'pegasi',
    decks: 103,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Pegasus',
  },
  {
    name: 'Elders',
    slug: 'elders',
    decks: 100,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Elder',
  },
  {
    name: 'Goats',
    slug: 'goats',
    decks: 98,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Goat',
  },
  {
    name: 'Elephants',
    slug: 'elephants',
    decks: 97,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Elephant',
  },
  {
    name: 'Sharks',
    slug: 'sharks',
    decks: 88,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Shark',
  },
  {
    name: 'Berserkers',
    slug: 'berserkers',
    decks: 87,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Berserker',
  },
  {
    name: 'Barbarians',
    slug: 'barbarians',
    decks: 78,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Barbarian',
  },
  {
    name: 'Kor',
    slug: 'kor',
    decks: 58,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Kor',
  },
  {
    name: 'Specters',
    slug: 'specters',
    decks: 58,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Specter',
  },
  {
    name: 'Cephalids',
    slug: 'cephalids',
    decks: 43,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
  },
  {
    name: 'Symbiotes',
    slug: 'symbiotes',
    decks: 40,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Symbiote',
  },
  {
    name: 'Bards',
    slug: 'bards',
    decks: 34,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Bard',
  },
  {
    name: 'Minions',
    slug: 'minions',
    decks: 32,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Minion',
  },
  {
    name: 'Ogres',
    slug: 'ogres',
    decks: 29,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Ogre',
  },
  {
    name: 'Shades',
    slug: 'shades',
    decks: 23,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Shade',
  },
  {
    name: 'Nobles',
    slug: 'nobles',
    decks: 18,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Noble',
  },
  {
    name: 'Crocodiles',
    slug: 'crocodiles',
    decks: 11,
    list: 'typal',
    archetype: 'tribal',
    axes: ['tribal'],
    tribe: 'Crocodile',
  },
];
