/**
 * Real cards (Scryfall oracle_cards bulk, 2026-09-29) for the Coach tests:
 * the premium, land-swap, replace-when-full, settings and gem guards (T171
 * lane M). Fields copied verbatim from the bulk record, trimmed to what the
 * engines read; prices are that day's USD.
 */
import type { ScryfallCard } from '@/deck-builder/types';
import { encodeSnapshot, type Snapshot } from '../../cardFacts/codec';
import { extractCardFacts } from '../../cardFacts/extract';
import { CARD_FACTS_VERSION, type FactsInputCard } from '../../cardFacts/schema';

export const COACH_CARDS = {
  'Path to Exile': {
    id: '22e08a78-55b7-46b0-bd1a-a51548fc1861',
    oracle_id: 'd683d985-9888-4d21-8b5f-69e69ce4a03b',
    name: 'Path to Exile',
    layout: 'normal',
    mana_cost: '{W}',
    cmc: 1.0,
    type_line: 'Instant',
    oracle_text:
      'Exile target creature. Its controller may search their library for a basic land card, put that card onto the battlefield tapped, then shuffle.',
    colors: ['W'],
    color_identity: ['W'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 15,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.75',
    },
  },
  'Swords to Plowshares': {
    id: 'f7e12477-d59f-442b-a678-1be746d0b7be',
    oracle_id: 'b1544f21-7e98-461b-aed5-e748b0168c52',
    name: 'Swords to Plowshares',
    layout: 'normal',
    mana_cost: '{W}',
    cmc: 1.0,
    type_line: 'Instant',
    oracle_text: 'Exile target creature. Its controller gains life equal to its power.',
    colors: ['W'],
    color_identity: ['W'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 11,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.02',
    },
  },
  'Fierce Guardianship': {
    id: 'f7f3dd95-bd14-4e0f-a388-444f9cf1b0dc',
    oracle_id: 'd09c9cba-fdd2-479b-ad5d-d05181c3e3f9',
    name: 'Fierce Guardianship',
    layout: 'normal',
    mana_cost: '{2}{U}',
    cmc: 3.0,
    type_line: 'Instant',
    oracle_text:
      'If you control a commander, you may cast this spell without paying its mana cost.\nCounter target noncreature spell.',
    colors: ['U'],
    color_identity: ['U'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 83,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '65.16',
    },
  },
  'Imperial Seal': {
    id: 'e71a6bd3-7478-4c3a-8ae0-98352ce28492',
    oracle_id: '16cd0b90-f70c-4efa-b252-8de8784ef9a3',
    name: 'Imperial Seal',
    layout: 'normal',
    mana_cost: '{B}',
    cmc: 1.0,
    type_line: 'Sorcery',
    oracle_text:
      'Search your library for a card, then shuffle and put that card on top. You lose 2 life.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'mythic',
    edhrec_rank: 531,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '171.88',
    },
  },
  'The One Ring': {
    id: 'd5806e68-1054-458e-866d-1f2470f682b2',
    oracle_id: '3aa83ed2-f48b-4ce6-a614-2c54ddf50538',
    name: 'The One Ring',
    layout: 'normal',
    mana_cost: '{4}',
    cmc: 4.0,
    type_line: 'Legendary Artifact',
    oracle_text:
      'Indestructible\nWhen The One Ring enters, if you cast it, you gain protection from everything until your next turn.\nAt the beginning of your upkeep, you lose 1 life for each burden counter on The One Ring.\n{T}: Put a burden counter on The One Ring, then draw a card for each burden counter on The One Ring.',
    colors: [],
    color_identity: [],
    keywords: ['Indestructible'],
    rarity: 'mythic',
    edhrec_rank: 95,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '115.29',
    },
  },
  'Swiftfoot Boots': {
    id: '03f7e9fc-8e59-45c1-90fc-1d04d929b292',
    oracle_id: 'c8b143ad-43ec-4e0d-a440-e348daa31391',
    name: 'Swiftfoot Boots',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact — Equipment',
    oracle_text:
      "Equipped creature has hexproof and haste. (It can't be the target of spells or abilities your opponents control. It can attack and {T} no matter when it came under your control.)\nEquip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)",
    colors: [],
    color_identity: [],
    keywords: ['Equip'],
    rarity: 'uncommon',
    edhrec_rank: 12,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '2.00',
    },
  },
  "Tamiyo's Safekeeping": {
    id: 'fd4b7ee2-de65-4288-872d-486065a4f226',
    oracle_id: 'bb2b324c-970a-4920-884e-c92ba49669f0',
    name: "Tamiyo's Safekeeping",
    layout: 'normal',
    mana_cost: '{G}',
    cmc: 1.0,
    type_line: 'Instant',
    oracle_text:
      'Target permanent you control gains hexproof and indestructible until end of turn. You gain 2 life. (A permanent with hexproof and indestructible can\'t be the target of spells or abilities your opponents control. Damage and effects that say "destroy" don\'t destroy it.)',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 468,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '6.09',
    },
  },
  'Basalt Monolith': {
    id: 'f79de5e7-1545-420c-bfe1-ee2444fca85b',
    oracle_id: '6b8cf2a0-b045-4d91-9d91-c602d40c6237',
    name: 'Basalt Monolith',
    layout: 'normal',
    mana_cost: '{3}',
    cmc: 3.0,
    type_line: 'Artifact',
    oracle_text:
      "This artifact doesn't untap during your untap step.\n{T}: Add {C}{C}{C}.\n{3}: Untap this artifact.",
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['C'],
    rarity: 'uncommon',
    edhrec_rank: 568,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '5.17',
    },
  },
  'Evolving Wilds': {
    id: 'c0318a48-30e4-4ef7-be3d-5e561c5ce428',
    oracle_id: 'a75445d3-1303-4bb5-89ad-26ea93fecd48',
    name: 'Evolving Wilds',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.',
    colors: [],
    color_identity: [],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 19,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.27',
    },
  },
  'Escape Tunnel': {
    id: '5df90940-15ea-418c-8547-6c75d69ec6d3',
    oracle_id: '0056fc91-4398-471c-b561-7ff99750ac8a',
    name: 'Escape Tunnel',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      "{T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.\n{T}, Sacrifice this land: Target creature with power 2 or less can't be blocked this turn.",
    colors: [],
    color_identity: [],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 797,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.21',
    },
  },
  'Jund Panorama': {
    id: '50d8346a-e0b5-41eb-be89-7d1eb0e84f28',
    oracle_id: 'f39f33ac-074d-442d-ae4c-1d694ee315f3',
    name: 'Jund Panorama',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}: Add {C}.\n{1}, {T}, Sacrifice this land: Search your library for a basic Swamp, Mountain, or Forest card, put it onto the battlefield tapped, then shuffle.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['C'],
    rarity: 'common',
    edhrec_rank: 5198,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.50',
    },
  },
  'Ash Barrens': {
    id: 'e8510205-4baa-4f1c-bf64-5d931e2ddf48',
    oracle_id: '58257464-278e-45fa-8e0b-bcd9a7500bc1',
    name: 'Ash Barrens',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}: Add {C}.\nBasic landcycling {1} ({1}, Discard this card: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.)',
    colors: [],
    color_identity: [],
    keywords: ['Landcycling', 'Basic landcycling', 'Typecycling', 'Cycling'],
    produced_mana: ['C'],
    rarity: 'common',
    edhrec_rank: 210,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.35',
    },
  },
  'Yavimaya, Cradle of Growth': {
    id: '4e4b6e22-93b2-4896-bba5-0ceaa5d8ea3c',
    oracle_id: '8dd5f5af-d2d8-4356-8617-8381081b930c',
    name: 'Yavimaya, Cradle of Growth',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Legendary Land',
    oracle_text: 'Each land is a Forest in addition to its other land types.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['G'],
    rarity: 'rare',
    edhrec_rank: 78,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '17.22',
    },
  },
  'Castle Garenbrig': {
    id: 'e3c2c66c-f7f0-41d5-a805-a129aeaf1b75',
    oracle_id: 'de75e5dd-8a52-406c-b55c-96d686885500',
    name: 'Castle Garenbrig',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      'This land enters tapped unless you control a Forest.\n{T}: Add {G}.\n{2}{G}{G}, {T}: Add six {G}. Spend this mana only to cast creature spells or activate abilities of creatures.',
    colors: [],
    color_identity: ['G'],
    keywords: [],
    produced_mana: ['G'],
    rarity: 'rare',
    edhrec_rank: 719,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '9.36',
    },
  },
  'Takenuma, Abandoned Mire': {
    id: '499037cc-a577-41cb-8ca2-5e117945634f',
    oracle_id: 'ac2dd694-d2f1-4025-8400-12332bdc882a',
    name: 'Takenuma, Abandoned Mire',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Legendary Land',
    oracle_text:
      '{T}: Add {B}.\nChannel — {3}{B}, Discard this card: Mill three cards, then return a creature or planeswalker card from your graveyard to your hand. This ability costs {1} less to activate for each legendary creature you control.',
    colors: [],
    color_identity: ['B'],
    keywords: ['Mill', 'Channel'],
    produced_mana: ['B'],
    rarity: 'rare',
    edhrec_rank: 244,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '10.92',
    },
  },
  'Reliquary Tower': {
    id: 'e2a27742-08c1-4153-af7f-25a7a98f585e',
    oracle_id: 'c23e5b80-08d2-4e24-9908-fe2aa4f30f6f',
    name: 'Reliquary Tower',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text: 'You have no maximum hand size.\n{T}: Add {C}.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['C'],
    rarity: 'uncommon',
    edhrec_rank: 10,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '3.96',
    },
  },
  'Overgrown Tomb': {
    id: 'ad7e18e2-c033-4b6c-86e8-d0e5cc824cfd',
    oracle_id: '975ec9a3-6f20-4177-8211-82526e092538',
    name: 'Overgrown Tomb',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land — Swamp Forest',
    oracle_text:
      "({T}: Add {B} or {G}.)\nAs this land enters, you may pay 2 life. If you don't, it enters tapped.",
    colors: [],
    color_identity: ['B', 'G'],
    keywords: [],
    produced_mana: ['B', 'G'],
    rarity: 'rare',
    edhrec_rank: 71,
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  'Breeding Pool': {
    id: '63e4dc07-c742-41bd-8301-861637908fd1',
    oracle_id: '20283c4a-f1f0-42f0-bc08-6da87474426b',
    name: 'Breeding Pool',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land — Forest Island',
    oracle_text:
      "({T}: Add {G} or {U}.)\nAs this land enters, you may pay 2 life. If you don't, it enters tapped.",
    colors: [],
    color_identity: ['G', 'U'],
    keywords: [],
    produced_mana: ['G', 'U'],
    rarity: 'rare',
    edhrec_rank: 59,
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  'Cavern of Souls': {
    id: '3aad15a2-8a1b-4460-9b06-e85863081878',
    oracle_id: '89ca686a-7c72-4d8f-9290-e89635624a83',
    name: 'Cavern of Souls',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      "As this land enters, choose a creature type.\n{T}: Add {C}.\n{T}: Add one mana of any color. Spend this mana only to cast a creature spell of the chosen type, and that spell can't be countered.",
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'C', 'G', 'R', 'U', 'W'],
    rarity: 'mythic',
    edhrec_rank: 111,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '52.07',
    },
  },
  'Public Thoroughfare': {
    id: '1f8b915f-3e82-4b05-b963-01ebff7a8f7b',
    oracle_id: 'de5b995c-9691-4555-9070-66bcbc29f955',
    name: 'Public Thoroughfare',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      'This land enters tapped.\nWhen this land enters, sacrifice it unless you tap an untapped artifact or land you control.\n{T}: Add one mana of any color.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'common',
    edhrec_rank: 8866,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.22',
    },
  },
  'Shimmerdrift Vale': {
    id: 'f09d98db-0176-41a7-b99b-ead29876cdab',
    oracle_id: '2ac34f3e-822d-4fde-99ca-a31c4d9503fd',
    name: 'Shimmerdrift Vale',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Snow Land',
    oracle_text:
      'This land enters tapped.\nAs this land enters, choose a color.\n{T}: Add one mana of the chosen color.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'common',
    edhrec_rank: 7111,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.25',
    },
  },
  'Mox Opal': {
    id: '56001a36-126b-4c08-af98-a6cc4d84210e',
    oracle_id: 'de2440de-e948-4811-903c-0bbe376ff64d',
    name: 'Mox Opal',
    layout: 'normal',
    mana_cost: '{0}',
    cmc: 0.0,
    type_line: 'Legendary Artifact',
    oracle_text:
      'Metalcraft — {T}: Add one mana of any color. Activate only if you control three or more artifacts.',
    colors: [],
    color_identity: [],
    keywords: ['Metalcraft'],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'mythic',
    edhrec_rank: 242,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '242.25',
    },
  },
  'Chrome Mox': {
    id: 'f340cbf7-5bbe-45b9-a4bf-d1caa500ff93',
    oracle_id: 'ec3d4466-547c-4e02-b1b5-a156ec4637e9',
    name: 'Chrome Mox',
    layout: 'normal',
    mana_cost: '{0}',
    cmc: 0.0,
    type_line: 'Artifact',
    oracle_text:
      "Imprint — When this artifact enters, you may exile a nonartifact, nonland card from your hand.\n{T}: Add one mana of any of the exiled card's colors.",
    colors: [],
    color_identity: [],
    keywords: ['Imprint'],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'mythic',
    edhrec_rank: 153,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '166.83',
    },
  },
  'Mana Vault': {
    id: 'c1a31d52-a407-4ded-bfca-cc812f11afa0',
    oracle_id: '736892cb-a34b-4bb9-b56c-e26e3db207a2',
    name: 'Mana Vault',
    layout: 'normal',
    mana_cost: '{1}',
    cmc: 1.0,
    type_line: 'Artifact',
    oracle_text:
      "This artifact doesn't untap during your untap step.\nAt the beginning of your upkeep, you may pay {4}. If you do, untap this artifact.\nAt the beginning of your draw step, if this artifact is tapped, it deals 1 damage to you.\n{T}: Add {C}{C}{C}.",
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['C'],
    rarity: 'mythic',
    edhrec_rank: 150,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '119.62',
    },
  },
  "Karn's Bastion": {
    id: '22017ec2-3552-4865-af76-dba042b141f5',
    oracle_id: '9fb8cd81-403a-4988-8f1c-b8eccf8abd9c',
    name: "Karn's Bastion",
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}: Add {C}.\n{4}, {T}: Proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)',
    colors: [],
    color_identity: [],
    keywords: ['Proliferate'],
    produced_mana: ['C'],
    rarity: 'rare',
    edhrec_rank: 206,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '2.44',
    },
  },
  'Indatha Triome': {
    id: '2b74bb81-fb9a-40e5-a941-e517430b52f5',
    oracle_id: 'ec2b3779-55f7-4169-aa66-6312fb52721f',
    name: 'Indatha Triome',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land — Plains Swamp Forest',
    oracle_text:
      '({T}: Add {W}, {B}, or {G}.)\nThis land enters tapped.\nCycling {3} ({3}, Discard this card: Draw a card.)',
    colors: [],
    color_identity: ['B', 'G', 'W'],
    keywords: ['Cycling'],
    produced_mana: ['B', 'G', 'W'],
    rarity: 'rare',
    edhrec_rank: 481,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '17.55',
    },
  },
  'Command Tower': {
    id: '1ac6cb62-45da-4e9a-84c6-09e6eacf0664',
    oracle_id: '0895c9b7-ae7d-4bb3-af17-3b75deb50a25',
    name: 'Command Tower',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text: "{T}: Add one mana of any color in your commander's color identity.",
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'common',
    edhrec_rank: 2,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.56',
    },
  },
  'Polluted Delta': {
    id: '6e288374-2b71-4ace-b1d2-a19fee6cb4af',
    oracle_id: 'ef86989d-ce80-4e55-aece-7d11710eeffa',
    name: 'Polluted Delta',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}, Pay 1 life, Sacrifice this land: Search your library for an Island or Swamp card, put it onto the battlefield, then shuffle.',
    colors: [],
    color_identity: [],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 36,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '19.14',
    },
  },
  'Golgari Rot Farm': {
    id: '42486edd-24b7-4299-84fa-50559917b2a8',
    oracle_id: '1b301478-b14f-4ef8-94e6-9647d582eabe',
    name: 'Golgari Rot Farm',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      "This land enters tapped.\nWhen this land enters, return a land you control to its owner's hand.\n{T}: Add {B}{G}.",
    colors: [],
    color_identity: ['B', 'G'],
    keywords: [],
    produced_mana: ['B', 'G'],
    rarity: 'uncommon',
    edhrec_rank: 335,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.36',
    },
  },
  'Sol Ring': {
    id: '8ee443cc-e17a-493b-9c93-1f9e141a30e4',
    oracle_id: '6ad8011d-3471-4369-9d68-b264cc027487',
    name: 'Sol Ring',
    layout: 'normal',
    mana_cost: '{1}',
    cmc: 1.0,
    type_line: 'Artifact',
    oracle_text: '{T}: Add {C}{C}.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['C'],
    rarity: 'uncommon',
    edhrec_rank: 1,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.54',
    },
  },
  'Llanowar Wastes': {
    id: '266316d3-3bbc-4283-aab8-69629855909f',
    oracle_id: '32116127-cf96-4a1b-8896-a1ebc087b597',
    name: 'Llanowar Wastes',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text: '{T}: Add {C}.\n{T}: Add {B} or {G}. This land deals 1 damage to you.',
    colors: [],
    color_identity: ['B', 'G'],
    keywords: [],
    produced_mana: ['B', 'C', 'G'],
    rarity: 'rare',
    edhrec_rank: 137,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.77',
    },
  },
  'Woodland Cemetery': {
    id: '4d6f6c96-f813-4864-b4e1-b2a0aa8be1e8',
    oracle_id: 'c9fe1383-1331-4a58-a45a-3320250221a9',
    name: 'Woodland Cemetery',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      'This land enters tapped unless you control a Swamp or a Forest.\n{T}: Add {B} or {G}.',
    colors: [],
    color_identity: ['B', 'G'],
    keywords: [],
    produced_mana: ['B', 'G'],
    rarity: 'rare',
    edhrec_rank: 110,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.07',
    },
  },
  'Jungle Hollow': {
    id: 'ea13440b-3f7b-4182-9541-27c1fa3121e5',
    oracle_id: '6de714e1-446d-4fb9-9e3d-bcd3ec6af9ca',
    name: 'Jungle Hollow',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      'This land enters tapped.\nWhen this land enters, you gain 1 life.\n{T}: Add {B} or {G}.',
    colors: [],
    color_identity: ['B', 'G'],
    keywords: [],
    produced_mana: ['B', 'G'],
    rarity: 'common',
    edhrec_rank: 787,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.24',
    },
  },
  'Archfiend of Ifnir': {
    id: '83057af6-cb88-4401-92ef-5b5d10463140',
    oracle_id: '535e2af0-7b08-4026-b1bf-87626407dd42',
    name: 'Archfiend of Ifnir',
    layout: 'normal',
    mana_cost: '{3}{B}{B}',
    cmc: 5.0,
    type_line: 'Creature — Demon',
    oracle_text:
      'Flying\nWhenever you cycle or discard another card, put a -1/-1 counter on each creature your opponents control.\nCycling {2} ({2}, Discard this card: Draw a card.)',
    colors: ['B'],
    color_identity: ['B'],
    keywords: ['Flying', 'Cycling'],
    power: '5',
    toughness: '4',
    rarity: 'rare',
    edhrec_rank: 1288,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.31',
    },
  },
  'Beast Within': {
    id: '400b43aa-c1d2-4435-b863-061f43889422',
    oracle_id: '7735eeba-693b-47e2-bd51-414379cf1016',
    name: 'Beast Within',
    layout: 'normal',
    mana_cost: '{2}{G}',
    cmc: 3.0,
    type_line: 'Instant',
    oracle_text:
      'Destroy target permanent. Its controller creates a 3/3 green Beast creature token.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 25,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.62',
    },
  },
  "Kodama's Reach": {
    id: '90c423cc-1264-4067-9c50-e7c88c68ef2d',
    oracle_id: '1593ea18-2f2f-4ab4-83fb-6ccc0bec8a90',
    name: "Kodama's Reach",
    layout: 'normal',
    mana_cost: '{2}{G}',
    cmc: 3.0,
    type_line: 'Sorcery — Arcane',
    oracle_text:
      'Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 37,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.94',
    },
  },
  'Rampant Growth': {
    id: 'b7c47024-5e08-4b17-b41a-7647f8b814b9',
    oracle_id: '8539f295-5d58-4436-a73a-b9277c4c7795',
    name: 'Rampant Growth',
    layout: 'normal',
    mana_cost: '{1}{G}',
    cmc: 2.0,
    type_line: 'Sorcery',
    oracle_text:
      'Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 27,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.81',
    },
  },
  'Mind Stone': {
    id: 'b30a8f92-ce42-4b27-a893-bcf97fde228d',
    oracle_id: 'c97361b5-af16-4a7b-af85-a429dbaf4ad2',
    name: 'Mind Stone',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: '{T}: Add {C}.\n{1}, {T}, Sacrifice this artifact: Draw a card.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['C'],
    rarity: 'uncommon',
    edhrec_rank: 32,
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  'Blood Artist': {
    id: 'b5275d76-2947-4219-be21-614c7421614a',
    oracle_id: '310f141c-7f37-4729-aed6-dd9c09db448d',
    name: 'Blood Artist',
    layout: 'normal',
    mana_cost: '{1}{B}',
    cmc: 2.0,
    type_line: 'Creature — Vampire',
    oracle_text:
      'Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    power: '0',
    toughness: '1',
    rarity: 'uncommon',
    edhrec_rank: 141,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '3.92',
    },
  },
  'Zulaport Cutthroat': {
    id: 'c43609fb-3cee-44e0-98d0-3ecaba1d5767',
    oracle_id: '76b003e0-15af-4f22-bdf2-1ade5430964a',
    name: 'Zulaport Cutthroat',
    layout: 'normal',
    mana_cost: '{1}{B}',
    cmc: 2.0,
    type_line: 'Creature — Human Rogue Ally',
    oracle_text:
      'Whenever this creature or another creature you control dies, each opponent loses 1 life and you gain 1 life.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    power: '1',
    toughness: '1',
    rarity: 'uncommon',
    edhrec_rank: 236,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.34',
    },
  },
  'Fell the Profane // Fell Mire': {
    id: 'a3cb782d-c459-468d-9779-9b5669abc337',
    oracle_id: '053a69d8-2b5e-4f14-8b02-ca405891dc4a',
    name: 'Fell the Profane // Fell Mire',
    layout: 'modal_dfc',
    cmc: 4.0,
    type_line: 'Instant // Land',
    color_identity: ['B'],
    keywords: [],
    produced_mana: ['B'],
    rarity: 'uncommon',
    edhrec_rank: 200,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '4.92',
    },
    card_faces: [
      {
        name: 'Fell the Profane',
        mana_cost: '{2}{B}{B}',
        type_line: 'Instant',
        oracle_text: 'Destroy target creature or planeswalker.',
        colors: ['B'],
      },
      {
        name: 'Fell Mire',
        mana_cost: '',
        type_line: 'Land',
        oracle_text:
          "As this land enters, you may pay 3 life. If you don't, it enters tapped.\n{T}: Add {B}.",
        colors: [],
      },
    ],
  },
  'Rhystic Study': {
    id: '9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b',
    oracle_id: '53236dd7-845a-444c-96d5-f41ed7325d8f',
    name: 'Rhystic Study',
    layout: 'normal',
    mana_cost: '{2}{U}',
    cmc: 3.0,
    type_line: 'Enchantment',
    oracle_text:
      'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.',
    colors: ['U'],
    color_identity: ['U'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 46,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '70.36',
    },
  },
  'Dark Ritual': {
    id: '11e12a84-e7be-4afc-a230-c2e644743fa8',
    oracle_id: '53f7c868-b03e-4fc2-8dcf-a75bbfa3272b',
    name: 'Dark Ritual',
    layout: 'normal',
    mana_cost: '{B}',
    cmc: 1.0,
    type_line: 'Instant',
    oracle_text: 'Add {B}{B}{B}.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    produced_mana: ['B'],
    rarity: 'uncommon',
    edhrec_rank: 33,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '7.12',
    },
  },
  'Demonic Tutor': {
    id: 'a24b4cb6-cebb-428b-8654-74347a6a8d63',
    oracle_id: '82004860-e589-4e38-8d61-8c0210e4ea39',
    name: 'Demonic Tutor',
    layout: 'normal',
    mana_cost: '{1}{B}',
    cmc: 2.0,
    type_line: 'Sorcery',
    oracle_text: 'Search your library for a card, put that card into your hand, then shuffle.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'mythic',
    edhrec_rank: 63,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '67.78',
    },
  },
  'Supreme Verdict': {
    id: '3892f1c5-937e-4ef4-b6f9-e0c0ded070d0',
    oracle_id: '0230de18-8d15-4cfa-9d42-7ccddd9f9570',
    name: 'Supreme Verdict',
    layout: 'normal',
    mana_cost: '{1}{W}{W}{U}',
    cmc: 4.0,
    type_line: 'Sorcery',
    oracle_text: "This spell can't be countered.\nDestroy all creatures.",
    colors: ['U', 'W'],
    color_identity: ['U', 'W'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 472,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '2.32',
    },
  },
  'Wrath of God': {
    id: '537d2b05-3f52-45d6-8fe3-26282085d0c6',
    oracle_id: '34515b16-c9a4-4f98-8c77-416a7a523407',
    name: 'Wrath of God',
    layout: 'normal',
    mana_cost: '{2}{W}{W}',
    cmc: 4.0,
    type_line: 'Sorcery',
    oracle_text: "Destroy all creatures. They can't be regenerated.",
    colors: ['W'],
    color_identity: ['W'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 676,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '4.14',
    },
  },
  'Crib Swap': {
    id: '8f2fb3c6-af75-47a3-9f97-521872c32890',
    oracle_id: '2987c385-011a-4032-a516-a46d1e9dc9e8',
    name: 'Crib Swap',
    layout: 'normal',
    mana_cost: '{2}{W}',
    cmc: 3.0,
    type_line: 'Kindred Instant — Shapeshifter',
    oracle_text:
      'Changeling (This card is every creature type.)\nExile target creature. Its controller creates a 1/1 colorless Shapeshifter creature token with changeling.',
    colors: ['W'],
    color_identity: ['W'],
    keywords: ['Changeling'],
    rarity: 'uncommon',
    edhrec_rank: 2457,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.22',
    },
  },
  'Doom Blade': {
    id: '5dcd0c4e-4047-47a2-8969-c62616d457c2',
    oracle_id: '59e7f2ae-4535-4191-98be-3e65b6b2befa',
    name: 'Doom Blade',
    layout: 'normal',
    mana_cost: '{1}{B}',
    cmc: 2.0,
    type_line: 'Instant',
    oracle_text: 'Destroy target nonblack creature.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 2204,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.27',
    },
  },
  'Beast Whisperer': {
    id: 'daf4bcd2-3ae4-4803-9ea1-3bcc3de5ca59',
    oracle_id: '5da7eea8-bb9e-47ce-a554-8a1ee058bd7a',
    name: 'Beast Whisperer',
    layout: 'normal',
    mana_cost: '{2}{G}{G}',
    cmc: 4.0,
    type_line: 'Creature — Elf Druid',
    oracle_text: 'Whenever you cast a creature spell, draw a card.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    power: '2',
    toughness: '3',
    rarity: 'rare',
    edhrec_rank: 213,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '9.03',
    },
  },
  'Accumulate Wisdom': {
    id: 'a6335319-6c92-40d4-ab2d-c06c79049c30',
    oracle_id: 'a63eb744-71c4-447d-9372-c3a734f022c5',
    name: 'Accumulate Wisdom',
    layout: 'normal',
    mana_cost: '{1}{U}',
    cmc: 2.0,
    type_line: 'Instant — Lesson',
    oracle_text:
      'Look at the top three cards of your library. Put one of those cards into your hand and the rest on the bottom of your library in any order. Put each of those cards into your hand instead if there are three or more Lesson cards in your graveyard.',
    colors: ['U'],
    color_identity: ['U'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 5615,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.24',
    },
  },
  'Village Rites': {
    id: '42ed35e9-51cd-468a-86a9-9412553cf50d',
    oracle_id: '365548fb-5acc-4a8a-b20b-26d28b7d029f',
    name: 'Village Rites',
    layout: 'normal',
    mana_cost: '{B}',
    cmc: 1.0,
    type_line: 'Instant',
    oracle_text: 'As an additional cost to cast this spell, sacrifice a creature.\nDraw two cards.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 202,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.85',
    },
  },
  'Deadly Rollick': {
    id: '0e13f735-54fa-42b6-aea4-ced33811d7d4',
    oracle_id: '0456ec64-2c81-4763-a352-8ff64a4c3d6b',
    name: 'Deadly Rollick',
    layout: 'normal',
    mana_cost: '{3}{B}',
    cmc: 4.0,
    type_line: 'Instant',
    oracle_text:
      'If you control a commander, you may cast this spell without paying its mana cost.\nExile target creature.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 107,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '28.38',
    },
  },
  'Mystic Remora': {
    id: '40140991-cffa-4b52-9a25-37e9a8aa9ddd',
    oracle_id: '8a52f3c0-2552-4425-b2e3-5496eb2232a7',
    name: 'Mystic Remora',
    layout: 'normal',
    mana_cost: '{U}',
    cmc: 1.0,
    type_line: 'Enchantment',
    oracle_text:
      'Cumulative upkeep {1} (At the beginning of your upkeep, put an age counter on this permanent, then sacrifice it unless you pay its upkeep cost for each age counter on it.)\nWhenever an opponent casts a noncreature spell, you may draw a card unless that player pays {4}.',
    colors: ['U'],
    color_identity: ['U'],
    keywords: ['Cumulative upkeep'],
    rarity: 'rare',
    edhrec_rank: 100,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '14.43',
    },
  },
  'Exotic Orchard': {
    id: 'd11c5fe0-1528-4c94-a8cc-42bcab9d7487',
    oracle_id: '27b047e3-0d41-45e2-98e9-9391d7923a1e',
    name: 'Exotic Orchard',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text: '{T}: Add one mana of any color that a land an opponent controls could produce.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'rare',
    edhrec_rank: 9,
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  'Diabolic Tutor': {
    id: 'd650dd8c-edd8-44e4-ae95-aaaf84557a72',
    oracle_id: '14589b6b-1814-46f9-a364-83cc15dacac2',
    name: 'Diabolic Tutor',
    layout: 'normal',
    mana_cost: '{2}{B}{B}',
    cmc: 4.0,
    type_line: 'Sorcery',
    oracle_text: 'Search your library for a card, put that card into your hand, then shuffle.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 485,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '2.22',
    },
  },
  'Diregraf Colossus': {
    id: '02351d67-2d73-43e3-82f7-5277c532d7ac',
    oracle_id: 'fd62ad01-601f-4250-bc2a-8ef3982e45c4',
    name: 'Diregraf Colossus',
    layout: 'normal',
    mana_cost: '{2}{B}',
    cmc: 3.0,
    type_line: 'Creature — Zombie Giant',
    oracle_text:
      'This creature enters with a +1/+1 counter on it for each Zombie card in your graveyard.\nWhenever you cast a Zombie spell, create a tapped 2/2 black Zombie creature token.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    power: '2',
    toughness: '2',
    rarity: 'rare',
    edhrec_rank: 2120,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '5.06',
    },
  },
  'Scroll Rack': {
    id: 'dfaaa58d-89bb-4cb3-96a6-b480e6f6954e',
    oracle_id: '648bd03d-247e-4d6f-87a9-12a67688cbf5',
    name: 'Scroll Rack',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text:
      '{1}, {T}: Exile any number of cards from your hand face down. Put that many cards from the top of your library into your hand. Then look at the exiled cards and put them on top of your library in any order.',
    colors: [],
    color_identity: [],
    keywords: [],
    rarity: 'mythic',
    edhrec_rank: 1373,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '29.16',
    },
  },
  'Lotus Petal': {
    id: 'f85ab5f9-508e-45de-8fa1-ce1f16552ffc',
    oracle_id: '32e5339e-9e4f-46f8-b305-f9d6d3ba8bb5',
    name: 'Lotus Petal',
    layout: 'normal',
    mana_cost: '{0}',
    cmc: 0.0,
    type_line: 'Artifact',
    oracle_text: '{T}, Sacrifice this artifact: Add one mana of any color.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'uncommon',
    edhrec_rank: 120,
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  'Talisman of Indulgence': {
    id: '36bd614f-ab3b-4ad1-ab5c-a7ca0a641f32',
    oracle_id: '1d9aeaaa-66f6-41cb-9bac-162d6fd8662c',
    name: 'Talisman of Indulgence',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: '{T}: Add {C}.\n{T}: Add {B} or {R}. This artifact deals 1 damage to you.',
    colors: [],
    color_identity: ['B', 'R'],
    keywords: [],
    produced_mana: ['B', 'C', 'R'],
    rarity: 'uncommon',
    edhrec_rank: 129,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.12',
    },
  },
  'Scheming Symmetry': {
    id: '01acc50b-856d-442d-9880-1a892b40643b',
    oracle_id: '6dfb50d7-359b-4644-90e3-7ecdacee7c12',
    name: 'Scheming Symmetry',
    layout: 'normal',
    mana_cost: '{B}',
    cmc: 1.0,
    type_line: 'Sorcery',
    oracle_text:
      'Choose two target players. Each of them searches their library for a card, then shuffles and puts that card on top.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 1838,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '9.34',
    },
  },
  'Goblin Lackey': {
    id: '30104836-1e9d-4533-98f8-d5c4e6484b52',
    oracle_id: '213fbbdd-f1bc-4bba-9124-7b26e9a706c8',
    name: 'Goblin Lackey',
    layout: 'normal',
    mana_cost: '{R}',
    cmc: 1.0,
    type_line: 'Creature — Goblin',
    oracle_text:
      'Whenever this creature deals damage to a player, you may put a Goblin permanent card from your hand onto the battlefield.',
    colors: ['R'],
    color_identity: ['R'],
    keywords: [],
    power: '1',
    toughness: '1',
    rarity: 'rare',
    edhrec_rank: 4856,
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  'Death Baron': {
    id: '34a27142-cf45-4164-9e10-373e5c8bf7c6',
    oracle_id: '99024aa8-5687-4d38-8a4b-feef42d6c1ff',
    name: 'Death Baron',
    layout: 'normal',
    mana_cost: '{1}{B}{B}',
    cmc: 3.0,
    type_line: 'Creature — Zombie Wizard',
    oracle_text:
      'Skeletons you control and other Zombies you control get +1/+1 and have deathtouch. (Any amount of damage they deal to a creature is enough to destroy it.)',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    power: '2',
    toughness: '2',
    rarity: 'rare',
    edhrec_rank: 1724,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '4.88',
    },
  },
  'Path of Ancestry': {
    id: 'b1aaa7b0-1cac-4a92-b880-7ef1ac00618f',
    oracle_id: 'b473e293-59e3-4e04-acf2-622604aeb25f',
    name: 'Path of Ancestry',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      "This land enters tapped.\n{T}: Add one mana of any color in your commander's color identity. When that mana is spent to cast a creature spell that shares a creature type with your commander, scry 1. (Look at the top card of your library. You may put that card on the bottom.)",
    colors: [],
    color_identity: [],
    keywords: ['Scry'],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'common',
    edhrec_rank: 14,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: null,
    },
  },
  'Reflecting Pool': {
    id: 'cbc4281a-b70d-4f96-b309-38e986484829',
    oracle_id: '67f43ac6-2a58-4b53-b5d7-0330e2a252e2',
    name: 'Reflecting Pool',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text: '{T}: Add one mana of any type that a land you control could produce.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'rare',
    edhrec_rank: 165,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '11.04',
    },
  },
  'Arcane Signet': {
    id: 'c6b6117c-faab-4bbb-b851-07bd8061ef03',
    oracle_id: '0bc7f093-bef0-4f1a-852c-4b75ebf54838',
    name: 'Arcane Signet',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: "{T}: Add one mana of any color in your commander's color identity.",
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'uncommon',
    edhrec_rank: 3,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.79',
    },
  },
  'Battle Angels of Tyr': {
    id: '4c91dbf4-94fa-45d0-b8ed-a778b11d789b',
    oracle_id: 'c2bd0c24-3973-48bc-a591-3779e3640c5d',
    name: 'Battle Angels of Tyr',
    layout: 'normal',
    mana_cost: '{2}{W}{W}',
    cmc: 4.0,
    type_line: 'Creature \u2014 Angel Knight',
    oracle_text:
      'Flying, myriad\nWhenever this creature deals combat damage to a player, draw a card if that player has more cards in hand than each other player. Then you create a Treasure token if that player controls more lands than each other player. Then you gain 3 life if that player has more life than each other player.',
    colors: ['W'],
    color_identity: ['W'],
    keywords: ['Myriad', 'Flying', 'Treasure'],
    power: '4',
    toughness: '4',
    rarity: 'mythic',
    edhrec_rank: 1781,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '28.89',
    },
  },
  'Blasphemous Act': {
    id: '7d4b1d44-126e-4987-9a9f-f0f9627a09cb',
    oracle_id: '7a2484a9-04fd-41a0-8224-610c1c07ed10',
    name: 'Blasphemous Act',
    layout: 'normal',
    mana_cost: '{8}{R}',
    cmc: 9.0,
    type_line: 'Sorcery',
    oracle_text:
      'This spell costs {1} less to cast for each creature on the battlefield.\nBlasphemous Act deals 13 damage to each creature.',
    colors: ['R'],
    color_identity: ['R'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 22,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.93',
    },
  },
  'Boros Signet': {
    id: '49c37c0e-d363-4033-a069-710241cd9923',
    oracle_id: '41c84665-1f99-40ab-aaca-1188649eb263',
    name: 'Boros Signet',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: '{1}, {T}: Add {R}{W}.',
    colors: [],
    color_identity: ['R', 'W'],
    keywords: [],
    produced_mana: ['R', 'W'],
    rarity: 'uncommon',
    edhrec_rank: 250,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.74',
    },
  },
  'Cathartic Reunion': {
    id: 'e3bca51a-b9be-4be2-a256-b15853fde433',
    oracle_id: '0f3c3e5f-6af3-4af2-8703-4ccc8ed8f675',
    name: 'Cathartic Reunion',
    layout: 'normal',
    mana_cost: '{1}{R}',
    cmc: 2.0,
    type_line: 'Sorcery',
    oracle_text: 'As an additional cost to cast this spell, discard two cards.\nDraw three cards.',
    colors: ['R'],
    color_identity: ['R'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 1106,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.25',
    },
  },
  'Coldsteel Heart': {
    id: 'b2548ad2-3c62-4ed1-899c-1002b46cdd8f',
    oracle_id: '21d700e8-0255-418e-96a0-6fe05b3f836d',
    name: 'Coldsteel Heart',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Snow Artifact',
    oracle_text:
      'This artifact enters tapped.\nAs this artifact enters, choose a color.\n{T}: Add one mana of the chosen color.',
    colors: [],
    color_identity: [],
    keywords: [],
    produced_mana: ['B', 'G', 'R', 'U', 'W'],
    rarity: 'uncommon',
    edhrec_rank: 2109,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '2.08',
    },
  },
  'Drakuseth, Maw of Flames': {
    id: '9e9b40f5-3dd0-4607-a78d-b004d57fa4ea',
    oracle_id: '060deaff-44d6-4f03-9568-bcb7add80255',
    name: 'Drakuseth, Maw of Flames',
    layout: 'normal',
    mana_cost: '{4}{R}{R}{R}',
    cmc: 7.0,
    type_line: 'Legendary Creature \u2014 Dragon',
    oracle_text:
      'Flying\nWhenever Drakuseth attacks, Drakuseth deals 4 damage to any target and 3 damage to each of up to two other targets.',
    colors: ['R'],
    color_identity: ['R'],
    keywords: ['Flying'],
    power: '7',
    toughness: '7',
    rarity: 'rare',
    edhrec_rank: 1120,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.50',
    },
  },
  'Elven Passage': {
    id: 'dd1fd2ab-2565-4798-a832-fc849df82f74',
    oracle_id: '97a2cd39-6b54-496b-b3ac-dab9dfed7edc',
    name: 'Elven Passage',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}, Pay 1 life, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle. You may behold an Elf. If you do, untap that land. (To behold an Elf, choose an Elf you control or reveal an Elf card from your hand.)',
    colors: [],
    color_identity: [],
    keywords: ['Behold'],
    rarity: 'rare',
    edhrec_rank: 8656,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.60',
    },
  },
  'Fable of the Mirror-Breaker // Reflection of Kiki-Jiki': {
    id: '24c0d87b-0049-4beb-b9cb-6f813b7aa7dc',
    oracle_id: 'c0957e5e-c71b-439c-931c-9f55d2f76ace',
    name: 'Fable of the Mirror-Breaker // Reflection of Kiki-Jiki',
    layout: 'transform',
    cmc: 3.0,
    type_line: 'Enchantment \u2014 Saga // Enchantment Creature \u2014 Goblin Shaman',
    color_identity: ['R'],
    keywords: ['Transform', 'Treasure'],
    rarity: 'rare',
    edhrec_rank: 1751,
    card_faces: [
      {
        name: 'Fable of the Mirror-Breaker',
        mana_cost: '{2}{R}',
        type_line: 'Enchantment \u2014 Saga',
        oracle_text:
          '(As this Saga enters and after your draw step, add a lore counter.)\nI \u2014 Create a 2/2 red Goblin Shaman creature token with "Whenever this token attacks, create a Treasure token."\nII \u2014 You may discard up to two cards. If you do, draw that many cards.\nIII \u2014 Exile this Saga, then return it to the battlefield transformed under your control.',
        colors: ['R'],
      },
      {
        name: 'Reflection of Kiki-Jiki',
        mana_cost: '',
        type_line: 'Enchantment Creature \u2014 Goblin Shaman',
        oracle_text:
          "{1}, {T}: Create a token that's a copy of another target nonlegendary creature you control, except it has haste. Sacrifice it at the beginning of the next end step.",
        power: '2',
        toughness: '2',
        colors: ['R'],
      },
    ],
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '6.15',
    },
  },
  'Faithless Looting': {
    id: 'fc019ffa-4461-4f3d-ab8d-e4d20e77ca0c',
    oracle_id: '3d6fa57a-aa53-4b5c-b8af-a7612c823117',
    name: 'Faithless Looting',
    layout: 'normal',
    mana_cost: '{R}',
    cmc: 1.0,
    type_line: 'Sorcery',
    oracle_text:
      'Draw two cards, then discard two cards.\nFlashback {2}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)',
    colors: ['R'],
    color_identity: ['R'],
    keywords: ['Flashback'],
    rarity: 'common',
    edhrec_rank: 98,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.43',
    },
  },
  'Goblin Instigator': {
    id: 'b36a1bc7-a080-4fb6-b975-c59bb33a090a',
    oracle_id: '8b022754-6d16-470e-b754-4df6e4f4709e',
    name: 'Goblin Instigator',
    layout: 'normal',
    mana_cost: '{1}{R}',
    cmc: 2.0,
    type_line: 'Creature \u2014 Goblin Rogue',
    oracle_text: 'When this creature enters, create a 1/1 red Goblin creature token.',
    colors: ['R'],
    color_identity: ['R'],
    keywords: [],
    power: '1',
    toughness: '1',
    rarity: 'common',
    edhrec_rank: 3267,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.39',
    },
  },
  'Hoarding Broodlord': {
    id: '386ce3c9-869d-461c-a3de-c8add3786f73',
    oracle_id: '18e856b5-aab7-4802-8cec-1d44dd95d9f7',
    name: 'Hoarding Broodlord',
    layout: 'normal',
    mana_cost: '{5}{B}{B}{B}',
    cmc: 8.0,
    type_line: 'Creature \u2014 Dragon',
    oracle_text:
      'Convoke\nFlying\nWhen this creature enters, search your library for a card, exile it face down, then shuffle. For as long as that card remains exiled, you may play it.\nSpells you cast from exile have convoke.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: ['Flying', 'Convoke'],
    power: '7',
    toughness: '6',
    rarity: 'rare',
    edhrec_rank: 1718,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '4.29',
    },
  },
  'Hymn to Tourach': {
    id: '3faa8c5e-9e1b-4cee-b322-a033bf33dcbc',
    oracle_id: '992d9a72-d34d-47d7-96fb-37f0efb515ef',
    name: 'Hymn to Tourach',
    layout: 'normal',
    mana_cost: '{B}{B}',
    cmc: 2.0,
    type_line: 'Sorcery',
    oracle_text: 'Target player discards two cards at random.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 9599,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.60',
    },
  },
  'Isshin, Two Heavens as One': {
    id: 'a062a004-984e-4b62-960c-af7288f7a3e9',
    oracle_id: '65114758-9a75-43a7-96e8-0aa68faa6b24',
    name: 'Isshin, Two Heavens as One',
    layout: 'normal',
    mana_cost: '{R}{W}{B}',
    cmc: 3.0,
    type_line: 'Legendary Creature \u2014 Human Samurai',
    oracle_text:
      'If a creature attacking causes a triggered ability of a permanent you control to trigger, that ability triggers an additional time.',
    colors: ['B', 'R', 'W'],
    color_identity: ['B', 'R', 'W'],
    keywords: [],
    power: '3',
    toughness: '4',
    rarity: 'rare',
    edhrec_rank: 1469,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '3.94',
    },
  },
  'Laelia, the Blade Reforged': {
    id: '2cb16354-1211-4230-90e2-4858ba68f348',
    oracle_id: 'a0be9bb2-3234-4c6c-b8ce-0879b1f43003',
    name: 'Laelia, the Blade Reforged',
    layout: 'normal',
    mana_cost: '{2}{R}',
    cmc: 3.0,
    type_line: 'Legendary Creature \u2014 Spirit Warrior',
    oracle_text:
      'Haste\nWhenever Laelia attacks, exile the top card of your library. You may play that card this turn.\nWhenever one or more cards are put into exile from your library and/or your graveyard, put a +1/+1 counter on Laelia.',
    colors: ['R'],
    color_identity: ['R'],
    keywords: ['Haste'],
    power: '2',
    toughness: '2',
    rarity: 'rare',
    edhrec_rank: 1335,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.30',
    },
  },
  'Lathril, Blade of the Elves': {
    id: '8d4e5480-a287-4a25-b855-a26dae555b1c',
    oracle_id: '9b568c34-ba0a-44a7-a0ee-bee3a37b3396',
    name: 'Lathril, Blade of the Elves',
    layout: 'normal',
    mana_cost: '{2}{B}{G}',
    cmc: 4.0,
    type_line: 'Legendary Creature \u2014 Elf Noble',
    oracle_text:
      "Menace (This creature can't be blocked except by two or more creatures.)\nWhenever Lathril deals combat damage to a player, create that many 1/1 green Elf Warrior creature tokens.\n{T}, Tap ten untapped Elves you control: Each opponent loses 10 life and you gain 10 life.",
    colors: ['B', 'G'],
    color_identity: ['B', 'G'],
    keywords: ['Menace'],
    power: '2',
    toughness: '3',
    rarity: 'rare',
    edhrec_rank: 2006,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.70',
    },
  },
  'Llanowar Elves': {
    id: 'cbcb0668-e88c-4462-b079-34f140c0277e',
    oracle_id: 'eaddc7cf-5d58-422a-ba00-6708dee2d853',
    name: 'Llanowar Elves',
    layout: 'token',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Token Creature \u2014 Elf Druid',
    oracle_text: '{T}: Add {G}.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    produced_mana: ['G'],
    power: '1',
    toughness: '1',
    rarity: 'common',
    legalities: {
      commander: 'not_legal',
    },
    prices: {
      usd: '0.31',
    },
  },
  'Mind Twist': {
    id: '9763ea41-55c4-4b0a-9dc2-91ad4938b343',
    oracle_id: '78f9c223-9982-4282-a496-a6f892f0a5bf',
    name: 'Mind Twist',
    layout: 'normal',
    mana_cost: '{X}{B}',
    cmc: 1.0,
    type_line: 'Sorcery',
    oracle_text: 'Target player discards X cards at random.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 12197,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: null,
    },
  },
  'Orzhov Signet': {
    id: '90894726-1940-4291-a05c-b85cefbfa344',
    oracle_id: 'de3dcb5d-775a-479f-99f5-d1883ed9b1b5',
    name: 'Orzhov Signet',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: '{1}, {T}: Add {W}{B}.',
    colors: [],
    color_identity: ['B', 'W'],
    keywords: [],
    produced_mana: ['B', 'W'],
    rarity: 'common',
    edhrec_rank: 188,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.37',
    },
  },
  'Rakdos Signet': {
    id: 'a263e71d-953f-4648-b326-33133cfa7e00',
    oracle_id: '3adb7681-977f-4a32-9ec8-51481b958268',
    name: 'Rakdos Signet',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: '{1}, {T}: Add {B}{R}.',
    colors: [],
    color_identity: ['B', 'R'],
    keywords: [],
    produced_mana: ['B', 'R'],
    rarity: 'uncommon',
    edhrec_rank: 168,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.73',
    },
  },
  'Ruinous Ultimatum': {
    id: '50c1d6ca-7789-46b5-bc89-85cc3915cb85',
    oracle_id: 'a6f38908-aa4f-4f99-a28e-85d11dab52e4',
    name: 'Ruinous Ultimatum',
    layout: 'normal',
    mana_cost: '{R}{R}{W}{W}{W}{B}{B}',
    cmc: 7.0,
    type_line: 'Sorcery',
    oracle_text: 'Destroy all nonland permanents your opponents control.',
    colors: ['B', 'R', 'W'],
    color_identity: ['B', 'R', 'W'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 651,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '2.31',
    },
  },
  'Talisman of Conviction': {
    id: 'a365885c-f7d9-4ea1-9125-5265055e5570',
    oracle_id: '6c326439-5620-4ec6-a56a-fe9c3d5d2a46',
    name: 'Talisman of Conviction',
    layout: 'normal',
    mana_cost: '{2}',
    cmc: 2.0,
    type_line: 'Artifact',
    oracle_text: '{T}: Add {C}.\n{T}: Add {R} or {W}. This artifact deals 1 damage to you.',
    colors: [],
    color_identity: ['R', 'W'],
    keywords: [],
    produced_mana: ['C', 'R', 'W'],
    rarity: 'uncommon',
    edhrec_rank: 151,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.41',
    },
  },
  "Tsabo's Decree": {
    id: '0c1a0ebd-1add-49e6-b5e6-5b26abb1de88',
    oracle_id: '4e0de4d9-7a30-4a2b-94ba-8239baad2a0a',
    name: "Tsabo's Decree",
    layout: 'normal',
    mana_cost: '{5}{B}',
    cmc: 6.0,
    type_line: 'Instant',
    oracle_text:
      "Choose a creature type. Target player reveals their hand and discards all creature cards of that type. Then destroy all creatures of that type that player controls. They can't be regenerated.",
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 23494,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '1.74',
    },
  },
  'Verdant Catacombs': {
    id: '94c229ea-90da-4aa0-bfda-b162fb3b5b8b',
    oracle_id: '67d60b24-d429-4ded-90d9-06e49f28c396',
    name: 'Verdant Catacombs',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Land',
    oracle_text:
      '{T}, Pay 1 life, Sacrifice this land: Search your library for a Swamp or Forest card, put it onto the battlefield, then shuffle.',
    colors: [],
    color_identity: [],
    keywords: [],
    rarity: 'rare',
    edhrec_rank: 48,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '29.72',
    },
  },
  'Waste Not': {
    id: '2f5500a2-c6d6-40d7-b586-59b854733160',
    oracle_id: '00fdcc19-88ed-46c3-91f0-095806228105',
    name: 'Waste Not',
    layout: 'normal',
    mana_cost: '{1}{B}',
    cmc: 2.0,
    type_line: 'Enchantment',
    oracle_text:
      'Whenever an opponent discards a creature card, create a 2/2 black Zombie creature token.\nWhenever an opponent discards a land card, add {B}{B}.\nWhenever an opponent discards a noncreature, nonland card, draw a card.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    produced_mana: ['B'],
    rarity: 'rare',
    edhrec_rank: 1246,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '8.78',
    },
  },
  'Undead Warchief': {
    id: '01482b0c-d05b-4356-9144-e044159f4dcb',
    oracle_id: 'e6af56bf-bd78-4801-8f6e-033cdd68de3d',
    name: 'Undead Warchief',
    layout: 'normal',
    mana_cost: '{2}{B}{B}',
    cmc: 4.0,
    type_line: 'Creature — Zombie',
    oracle_text:
      'Zombie spells you cast cost {1} less to cast.\nZombie creatures you control get +2/+1.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    power: '1',
    toughness: '1',
    rarity: 'uncommon',
    edhrec_rank: 2897,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '18.11',
    },
  },
  Aetherjacket: {
    id: '0a29c8a5-fd98-422c-9518-2db0993495e5',
    oracle_id: '062c8e40-dea7-4df7-bcaa-f1d696fe61c3',
    name: 'Aetherjacket',
    layout: 'normal',
    mana_cost: '{3}',
    cmc: 3.0,
    type_line: 'Artifact Creature — Thopter',
    oracle_text:
      'Flying, vigilance\n{2}, {T}, Sacrifice this creature: Destroy another target artifact. Activate only as a sorcery.',
    colors: [],
    color_identity: [],
    keywords: ['Flying', 'Vigilance'],
    power: '2',
    toughness: '1',
    rarity: 'common',
    edhrec_rank: 13867,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.15',
    },
  },
  Counterspell: {
    id: '4f616706-ec97-4923-bb1e-11a69fbaa1f8',
    oracle_id: 'cc187110-1148-4090-bbb8-e205694a39f5',
    name: 'Counterspell',
    layout: 'normal',
    mana_cost: '{U}{U}',
    cmc: 2.0,
    type_line: 'Instant',
    oracle_text: 'Counter target spell.',
    colors: ['U'],
    color_identity: ['U'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 16,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '3.72',
    },
  },
  Forest: {
    id: 'dce15387-4114-4b3e-91aa-5b42b45c44ac',
    oracle_id: 'b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6',
    name: 'Forest',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Basic Land — Forest',
    oracle_text: '({T}: Add {G}.)',
    colors: [],
    color_identity: ['G'],
    keywords: [],
    produced_mana: ['G'],
    rarity: 'common',
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  Swamp: {
    id: 'b7387103-1df1-4fd0-9e91-1544509792c7',
    oracle_id: '56719f6a-1a6c-4c0a-8d21-18f7d7350b68',
    name: 'Swamp',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Basic Land — Swamp',
    oracle_text: '({T}: Add {B}.)',
    colors: [],
    color_identity: ['B'],
    keywords: [],
    produced_mana: ['B'],
    rarity: 'common',
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  Island: {
    id: 'f3cc07cd-cc79-4745-b0b7-eade60175cc3',
    oracle_id: 'b2c6aa39-2d2a-459c-a555-fb48ba993373',
    name: 'Island',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Basic Land — Island',
    oracle_text: '({T}: Add {U}.)',
    colors: [],
    color_identity: ['U'],
    keywords: [],
    produced_mana: ['U'],
    rarity: 'common',
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  Plains: {
    id: '8ab0f4c0-b331-4c57-b68f-2e24bb5ba06c',
    oracle_id: 'bc71ebf6-2056-41f7-be35-b2e5c34afa99',
    name: 'Plains',
    layout: 'normal',
    mana_cost: '',
    cmc: 0.0,
    type_line: 'Basic Land — Plains',
    oracle_text: '({T}: Add {W}.)',
    colors: [],
    color_identity: ['W'],
    keywords: [],
    produced_mana: ['W'],
    rarity: 'common',
    legalities: {
      commander: 'legal',
    },
    prices: {},
  },
  Murder: {
    id: '2c249609-9cf7-46f1-b94c-9329add966bb',
    oracle_id: '938b4e2c-88d9-4637-bc00-e228920c9a78',
    name: 'Murder',
    layout: 'normal',
    mana_cost: '{1}{B}{B}',
    cmc: 3.0,
    type_line: 'Instant',
    oracle_text: 'Destroy target creature.',
    colors: ['B'],
    color_identity: ['B'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 861,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.22',
    },
  },
  Cultivate: {
    id: 'e60deb92-f7dd-4f4e-9036-e47dd586f985',
    oracle_id: '8b755881-a72d-4e21-a369-d2924eb4585a',
    name: 'Cultivate',
    layout: 'normal',
    mana_cost: '{2}{G}',
    cmc: 3.0,
    type_line: 'Sorcery',
    oracle_text:
      'Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 20,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.42',
    },
  },
  Harmonize: {
    id: 'bd7138fb-6aa7-455e-b1f7-ca08d747277d',
    oracle_id: '7eff84f1-f772-497a-b350-bbc93d0230f7',
    name: 'Harmonize',
    layout: 'normal',
    mana_cost: '{2}{G}{G}',
    cmc: 4.0,
    type_line: 'Sorcery',
    oracle_text: 'Draw three cards.',
    colors: ['G'],
    color_identity: ['G'],
    keywords: [],
    rarity: 'uncommon',
    edhrec_rank: 325,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.25',
    },
  },
  Machinate: {
    id: '49e815b3-373c-4b2e-beb5-c894a52ffdea',
    oracle_id: '545399a0-f1f5-40bc-bd40-038946df8ad7',
    name: 'Machinate',
    layout: 'normal',
    mana_cost: '{1}{U}{U}',
    cmc: 3.0,
    type_line: 'Instant',
    oracle_text:
      'Look at the top X cards of your library, where X is the number of artifacts you control. Put one of those cards into your hand and the rest on the bottom of your library in any order.',
    colors: ['U'],
    color_identity: ['U'],
    keywords: [],
    rarity: 'common',
    edhrec_rank: 20775,
    legalities: {
      commander: 'legal',
    },
    prices: {
      usd: '0.07',
    },
  },
} as unknown as Record<string, ScryfallCard>;

/** A card-facts snapshot of every card above, for `setCardFactsSnapshot`. */
export function coachCardFactsSnapshot(): Snapshot {
  const cards = Object.values(COACH_CARDS) as unknown as FactsInputCard[];
  return JSON.parse(
    JSON.stringify(
      encodeSnapshot(
        {
          generatedAt: '2026-09-29T09:01:56.000Z',
          sources: {
            scryfallOracleCards: {
              updatedAt: '2026-09-29T09:01:56.000Z',
              file: 'oracle-cards-20260929090156.jsonl.gz',
            },
            taggerTags: { generatedAt: '2026-09-01T22:03:33.453Z' },
          },
          extractor: { version: CARD_FACTS_VERSION, name: 'cardFacts/extract.ts' },
          llm: null,
          seeds: {},
          universe: 'test',
          cards: cards.length,
        },
        cards.map((c) => extractCardFacts(c))
      )
    )
  ) as Snapshot;
}
