// Loads + searches the bundled Magic Comprehensive Rules (public/comprehensive-rules.json,
// generated by scripts/refresh-rules.mjs). Powers the Rules Reference: keyword
// lookup, glossary, and full rule-number/text search. Fully offline — the bundle
// ships as a static asset.

export interface RuleEntry {
  number: string;
  text: string;
}
export interface GlossaryEntry {
  term: string;
  definition: string;
}
export interface KeywordEntry {
  name: string;
  rule: string;
  kind: 'ability' | 'action';
}
export interface RulesBundle {
  meta: { effective: string; source: string };
  sections: { number: string; title: string }[];
  rules: RuleEntry[];
  glossary: GlossaryEntry[];
  keywords: KeywordEntry[];
}

let cache: Promise<RulesBundle> | null = null;

/** Fetch + cache the rules bundle (singleton promise). */
export function loadRulesBundle(): Promise<RulesBundle> {
  if (!cache) {
    cache = fetch('/comprehensive-rules.json').then((r) => {
      if (!r.ok) throw new Error(`Failed to load rules (${r.status})`);
      return r.json() as Promise<RulesBundle>;
    });
  }
  return cache;
}

const norm = (s: string) => s.toLowerCase().trim();
const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export function searchKeywords(keywords: KeywordEntry[], query: string): KeywordEntry[] {
  const q = norm(query);
  if (!q) return keywords;
  return keywords.filter((k) => k.name.toLowerCase().includes(q));
}

export function searchGlossary(glossary: GlossaryEntry[], query: string): GlossaryEntry[] {
  const q = norm(query);
  if (!q) return glossary;
  // Term matches rank above definition-only matches.
  const term: GlossaryEntry[] = [];
  const def: GlossaryEntry[] = [];
  for (const g of glossary) {
    if (g.term.toLowerCase().includes(q)) term.push(g);
    else if (g.definition.toLowerCase().includes(q)) def.push(g);
  }
  return [...term, ...def];
}

/**
 * Search rules. A numeric query (e.g. "702.2" or "104") matches rule numbers by
 * prefix; anything else is a case-insensitive text search. Capped at `limit`.
 */
export function searchRules(rules: RuleEntry[], query: string, limit = 200): RuleEntry[] {
  const q = norm(query);
  if (!q) return rules.slice(0, limit);
  const out: RuleEntry[] = [];
  const byNumber = /^\d/.test(q);
  for (const r of rules) {
    const hit = byNumber ? r.number.startsWith(q) : r.text.toLowerCase().includes(q);
    if (hit) {
      out.push(r);
      if (out.length >= limit) break;
    }
  }
  return out;
}

/** A rule plus its lettered subrules, e.g. subrulesFor(rules, "702.2") → 702.2, 702.2a, 702.2b… */
export function subrulesFor(rules: RuleEntry[], ruleNumber: string): RuleEntry[] {
  const child = new RegExp(`^${escapeRe(ruleNumber)}[a-z]`);
  return rules.filter((r) => r.number === ruleNumber || child.test(r.number));
}
